In [137]:
import pandas as pd
import numpy as np

In [138]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", "{:.2f}".format)

In [242]:
app_train = pd.read_csv(r"D:\Projects\credit-risk-default-prediction\data\raw\application_train.csv")
app_train.shape

(307511, 122)

In [140]:
app_train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637,-3648.00,-2120,NaN,1,1,0,1,1,0,Laborers,1.00,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.08,0.26,0.14,0.02,0.04,0.97,0.62,0.01,0.00,0.07,0.08,0.12,0.04,0.02,0.02,0.00,0.00,0.03,0.04,0.97,0.63,0.01,0.00,0.07,0.08,0.12,0.04,0.02,0.02,0.00,0.00,0.03,0.04,0.97,0.62,0.01,0.00,0.07,0.08,0.12,0.04,0.02,0.02,0.00,0.00,reg oper account,block of flats,0.01,"Stone, brick",No,2.00,2.00,2.00,2.00,-1134.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188,-1186.00,-291,NaN,1,1,0,1,1,0,Core staff,2.00,1,1,MONDAY,11,0,0,0,0,0,0,School,0.31,0.62,NaN,0.10,0.05,0.99,0.80,0.06,0.08,0.03,0.29,0.33,0.01,0.08,0.05,0.00,0.01,0.09,0.05,0.99,0.80,0.05,0.08,0.03,0.29,0.33,0.01,0.08,0.06,0.00,0.00,0.10,0.05,0.99,0.80,0.06,0.08,0.03,0.29,0.33,0.01,0.08,0.06,0.00,0.01,reg oper account,block of flats,0.07,Block,No,1.00,0.00,1.00,0.00,-828.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225,-4260.00,-2531,26.00,1,1,1,1,1,0,Laborers,1.00,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.56,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-815.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039,-9833.00,-2437,NaN,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.00,2.00,0.00,-617.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038,-4311.00,-3458,NaN,1,1,0,1,0,0,Core staff,1.00,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-1106.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00

In [141]:
app_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), str(16)
memory usage: 286.2 MB

In [142]:
app_train.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.00,307511.00,307511.00,307511.00,307511.00,307499.00,307233.00,307511.00,307511.00,307511.00,307511.00,307511.00,104582.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307509.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,134133.00,306851.00,246546.00,151450.00,127568.00,157504.00,103023.00,92646.00,143620.00,152683.00,154491.00,98869.00,124921.00,97312.00,153161.00,93997.00,137829.00,151450.00,127568.00,157504.00,103023.00,92646.00,143620.00,152683.00,154491.00,98869.00,124921.00,97312.00,153161.00,93997.00,137829.00,151450.00,127568.00,157504.00,103023.00,92646.00,143620.00,152683.00,154491.00,98869.00,124921.00,97312.00,153161.00,93997.00,137829.00,159080.00,306490.00,306490.00,306490.00,306490.00,307510.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,265992.00,265992.00,265992.00,265992.00,265992.00,265992.00
mean,278180.52,0.08,0.42,168797.92,599026.00,27108.57,538396.21,0.02,-16037.00,63815.05,-4986.12,-2994.20,12.06,1.00,0.82,0.20,1.00,0.28,0.06,2.15,2.05,2.03,12.06,0.02,0.05,0.04,0.08,0.23,0.18,0.50,0.51,0.51,0.12,0.09,0.98,0.75,0.04,0.08,0.15,0.23,0.23,0.07,0.10,0.11,0.01,0.03,0.11,0.09,0.98,0.76,0.04,0.07,0.15,0.22,0.23,0.06,0.11,0.11,0.01,0.03,0.12,0.09,0.98,0.76,0.04,0.08,0.15,0.23,0.23,0.07,0.10,0.11,0.01,0.03,0.10,1.42,0.14,1.41,0.10,-962.86,0.00,0.71,0.00,0.02,0.09,0.00,0.08,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.03,0.27,0.27,1.90
std,102790.18,0.27,0.72,237123.15,402490.78,14493.74,369446.46,0.01,4363.99,141275.77,3522.89,1509.45,11.94,0.00,0.38,0.40,0.04,0.45,0.23,0.91,0.51,0.50,3.27,0.12,0.22,0.20,0.27,0.42,0.38,0.21,0.19,0.19,0.11,0.08,0.06,0.11,0.08,0.13,0.10,0.14,0.16,0.08,0.09,0.11,0.05,0.07,0.11,0.08,0.06,0.11,0.07,0.13,0.10,0.14,0.16,0.08,0.10,0.11,0.05,0.07,0.11,0.08,0.06,0.11,0.08,0.13,0.10,0.15,0.16,0.08,0.09,0.11,0.05,0.07,0.11,2.40,0.45,2.38,0.36,826.81,0.01,0.45,0.01,0.12,0.28,0.01,0.27,0.06,0.00,0.06,0.00,0.06,0.05,0.03,0.10,0.02,0.09,0.02,0.02,0.02,0.08,0.11,0.20,0.92,0.79,1.87
min,100002.00,0.00,0.00,25650.00,45000.00,1615.50,40500.00,0.00,-25229.00,-17912.00,-24672.00,-7197.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4292.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,189145.50,0.00,0.00,112500.00,270000.00,16524.00,238500.00,0.01,-19682.00,-2760.00,-7479.50,-4299.00,5.00,1.00,1.00,0.00,1.00,0.00,0.00,2.00,2.00,2.00,10.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33,0.39,0.37,0.06,0.04,0.98,0.69,0.01,0.00,0.07,0.17,0.08,0.02,0.05,0.05,0.00,0.00,0.05,0.04,0.98,0.70,0.01,0.00,0.07,0.17,0.08,0.02,0.05,0.04,0.00,0.00,0.06,0.04,0.98,0.69,0.01,0.00,0.07,0.17,0.08,0.02,0.05,0.05,0.00,0.00,0.04,0.00,0.00,0.00,0.00,-1570.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,278202.00,0.00,0.00,147150.00,513531.00,24903.00,450000.00,0.02,-15750.00,-1213.00,-4504.00,-3254.00,9.00,1.00,1.00,0.00,1.00,0.00,0.00,2.00,2.00,2.00,12.00,0.00,0.00,0.00,0.00,0.00,0.00,0.51,0.57,0.54,0.09,0.08,0.98,0.76,0.02,0.00,0.14,0.17,0.21,0.05,0.08,0.07,0.00,0.00,0.08,0.07,0.98,0.76,0.02,0.00,0.14,0.17,0.21,0.05,0.08,0.07,0.00,0.00,0.09,0.08,0.98,0.76,0.02,0.00,0.14,0.17,0.21,0.05,0.08,0.07,0.00,0.00,0.07,0.00,0.00,0.00,0.00,-757.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00
75%,367142.50,0.00,1.00,202500.00,808650.00,34596.00,679500.00,0.03,-12413.00,-289.00,-2010.00,-1720.00,15.00,1.00,1.00,0.00,1.00,1.00,0.00,3.00,2.00,2.00,14.00,0.00,0.00,0.00,0.00,0.00,0.00,0.68,0.66,0.67,0.15,0.11,0.99,0.82,0.05,0.12,0.21,0.33,0.38,0.09,0.12,0.13,0.00,0.03,0.14,0.11,0.99,0.82,0.05,0.12,0.21,0.33,0.38,0.08,0.13,0.13,0.00,0.02,0.15,0.11,0.99,0.83,0.05,0.12,0.21,0.33,0.38,0.09,0.12,0.13,0.00,0.03,0.13,2.00,0.00,2.00,0.00,-274.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00
max,456255.00,1.00,19.00,117000000.00,4050000.00,258025.50,4050000.00,0.07,-7489.00,365243.00,0.00,0.00,91.00,1.00,1.00,1.00,1.00,1.00,1.00,20.00,3.00,3.00,23.00,1.00,1.00,1.00,1.00,1.00,1.00,0.96,0.85,0.90,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,348.00,34.00,344.00,24.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,4.00,9.00,8.00,27.00,261.00,25.00

In [143]:
app_train.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    SK_ID_CURR                    307511 non-null  int64
 1    TARGET                        307511 non-null  int64
 2    NAME_CONTRACT_TYPE            307511 non-null  str
 3    CODE_GENDER                   307511 non-null  str
 4    FLAG_OWN_CAR                  307511 non-null  str
 5    FLAG_OWN_REALTY               307511 non-null  str
 6    CNT_CHILDREN                  307511 non-null  int64
 7    AMT_INCOME_TOTAL              307511 non-null  float64
 8    AMT_CREDIT                    307511 non-null  float64
 9    AMT_ANNUITY                   307499 non-null  float64
 10   AMT_GOODS_PRICE               307233 non-null  float64
 11   NAME_TYPE_SUITE               306219 non-null  str
 12   NAME_INCOME_TYPE              307511 non-null  str
 13   NAME_EDUCATION_TYPE           307511 non-null  str
 14   NAME_FAMILY_STATUS            307511 non-null  str
 15   NAME_HOUSING_TYPE             307511 non-null  str
 16   REGION_POPULATION_RELATIVE    307511 non-null  float64
 17   DAYS_BIRTH                    307511 non-null  int64
 18   DAYS_EMPLOYED                 307511 non-null  int64
 19   DAYS_REGISTRATION             307511 non-null  float64
 20   DAYS_ID_PUBLISH               307511 non-null  int64
 21   OWN_CAR_AGE                   104582 non-null  float64
 22   FLAG_MOBIL                    307511 non-null  int64
 23   FLAG_EMP_PHONE                307511 non-null  int64
 24   FLAG_WORK_PHONE               307511 non-null  int64
 25   FLAG_CONT_MOBILE              307511 non-null  int64
 26   FLAG_PHONE                    307511 non-null  int64
 27   FLAG_EMAIL                    307511 non-null  int64
 28   OCCUPATION_TYPE               211120 non-null  str
 29   CNT_FAM_MEMBERS               307509 non-null  float64
 30   REGION_RATING_CLIENT          307511 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    307511 non-null  str
 33   HOUR_APPR_PROCESS_START       307511 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    307511 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    307511 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   307511 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        307511 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        307511 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       307511 non-null  int64
 40   ORGANIZATION_TYPE             307511 non-null  str
 41   EXT_SOURCE_1                  134133 non-null  float64
 42   EXT_SOURCE_2                  306851 non-null  float64
 43   EXT_SOURCE_3                  246546 non-null  float64
 44   APARTMENTS_AVG                151450 non-null  float64
 45   BASEMENTAREA_AVG              127568 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 47   YEARS_BUILD_AVG               103023 non-null  float64
 48   COMMONAREA_AVG                92646 non-null   float64
 49   ELEVATORS_AVG                 143620 non-null  float64
 50   ENTRANCES_AVG                 152683 non-null  float64
 51   FLOORSMAX_AVG                 154491 non-null  float64
 52   FLOORSMIN_AVG                 98869 non-null   float64
 53   LANDAREA_AVG                  124921 non-null  float64
 54   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 55   LIVINGAREA_AVG                153161 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 57   NONLIVINGAREA_AVG             137829 non-null  float64
 58   APARTMENTS_MODE               151450 non-null  float64
 59   BASEMENTAREA_MODE             127568 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 61   YEARS_BUILD_MODE              103023 non-null  float64
 62   COMMONAREA_MODE               92646 non-null   float64
 63   ELEVATORS_MODE                143620 non-null  float64
 64   ENTRANCES_MODE                152683 non-null  float64
 65   FLOORSMAX_MODE                154491 non-null  float64
 66   FLOORSMIN_MODE                98869 non-null   float64
 67   LANDAREA_MODE                 124921 non-null  float64
 68   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 69   LIVINGAREA_MODE               153161 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 71   NONLIVINGAREA_MODE            137829 non-null  float64
 72   APARTMENTS_MEDI               151450 non-null  float64
 73   BASEMENTAREA_MEDI             127568 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 75   YEARS_BUILD_MEDI              103023 non-null  float64
 76   COMMONAREA_MEDI               92646 non-null   float64
 77   ELEVATORS_MEDI                143620 non-null  float64
 78   ENTRANCES_MEDI                152683 non-null  float64
 79   FLOORSMAX_MEDI                154491 non-null  float64
 80   FLOORSMIN_MEDI                98869 non-null   float64
 81   LANDAREA_MEDI                 124921 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 83   LIVINGAREA_MEDI               153161 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 85   NONLIVINGAREA_MEDI            137829 non-null  float64
 86   FONDKAPREMONT_MODE            97216 non-null   str
 87   HOUSETYPE_MODE                153214 non-null  str
 88   TOTALAREA_MODE                159080 non-null  float64
 89   WALLSMATERIAL_MODE            151170 non-null  str
 90   EMERGENCYSTATE_MODE           161756 non-null  str
 91   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 96   FLAG_DOCUMENT_2               307511 non-null  int64
 97   FLAG_DOCUMENT_3               307511 non-null  int64
 98   FLAG_DOCUMENT_4               307511 non-null  int64
 99   FLAG_DOCUMENT_5               307511 non-null  int64
 100  FLAG_DOCUMENT_6               307511 non-null  int64
 101  FLAG_DOCUMENT_7               307511 non-null  int64
 102  FLAG_DOCUMENT_8               307511 non-null  int64
 103  FLAG_DOCUMENT_9               307511 non-null  int64
 104  FLAG_DOCUMENT_10              307511 non-null  int64
 105  FLAG_DOCUMENT_11              307511 non-null  int64
 106  FLAG_DOCUMENT_12              307511 non-null  int64
 107  FLAG_DOCUMENT_13              307511 non-null  int64
 108  FLAG_DOCUMENT_14              307511 non-null  int64
 109  FLAG_DOCUMENT_15              307511 non-null  int64
 110  FLAG_DOCUMENT_16              307511 non-null  int64
 111  FLAG_DOCUMENT_17              307511 non-null  int64
 112  FLAG_DOCUMENT_18              307511 non-null  int64
 113  FLAG_DOCUMENT_19              307511 non-null  int64
 114  FLAG_DOCUMENT_20              307511 non-null  int64
 115  FLAG_DOCUMENT_21              307511 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: float64(65), int64(41), str(16)
memory usage: 286.2 MB

In [144]:
app_train.isnull()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True
307507,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True
307508,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
307509,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,True,True,False,False,True,True,True,False,True,True,False,True,False,True,True,True,False,False,True,True,True,False,True,True,False,True,False,True,True,True,False,False,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
307510,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,True,True,False,True,False,False,False,False,True,False,False,False,False,True,True,True,False,True,False,False,False,False,True,False,False,False,False,True,True,True,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [145]:
app_train.isnull().sum().sort_values(ascending=False).head(67)

COMMONAREA_AVG                  214865
COMMONAREA_MODE                 214865
COMMONAREA_MEDI                 214865
NONLIVINGAPARTMENTS_MEDI        213514
NONLIVINGAPARTMENTS_MODE        213514
NONLIVINGAPARTMENTS_AVG         213514
FONDKAPREMONT_MODE              210295
LIVINGAPARTMENTS_AVG            210199
LIVINGAPARTMENTS_MEDI           210199
LIVINGAPARTMENTS_MODE           210199
FLOORSMIN_MODE                  208642
FLOORSMIN_AVG                   208642
FLOORSMIN_MEDI                  208642
YEARS_BUILD_AVG                 204488
YEARS_BUILD_MODE                204488
YEARS_BUILD_MEDI                204488
OWN_CAR_AGE                     202929
LANDAREA_MEDI                   182590
LANDAREA_AVG                    182590
LANDAREA_MODE                   182590
BASEMENTAREA_MODE               179943
BASEMENTAREA_MEDI               179943
BASEMENTAREA_AVG                179943
EXT_SOURCE_1                    173378
NONLIVINGAREA_MODE              169682
NONLIVINGAREA_AVG               169682
NONLIVINGAREA_MEDI              169682
ELEVATORS_AVG                   163891
ELEVATORS_MEDI                  163891
ELEVATORS_MODE                  163891
WALLSMATERIAL_MODE              156341
APARTMENTS_AVG                  156061
APARTMENTS_MEDI                 156061
APARTMENTS_MODE                 156061
ENTRANCES_MODE                  154828
ENTRANCES_MEDI                  154828
ENTRANCES_AVG                   154828
LIVINGAREA_AVG                  154350
LIVINGAREA_MEDI                 154350
LIVINGAREA_MODE                 154350
HOUSETYPE_MODE                  154297
FLOORSMAX_MODE                  153020
FLOORSMAX_AVG                   153020
FLOORSMAX_MEDI                  153020
YEARS_BEGINEXPLUATATION_MODE    150007
YEARS_BEGINEXPLUATATION_MEDI    150007
YEARS_BEGINEXPLUATATION_AVG     150007
TOTALAREA_MODE                  148431
EMERGENCYSTATE_MODE             145755
OCCUPATION_TYPE                  96391
EXT_SOURCE_3                     60965
AMT_REQ_CREDIT_BUREAU_HOUR       41519
AMT_REQ_CREDIT_BUREAU_WEEK       41519
AMT_REQ_CREDIT_BUREAU_MON        41519
AMT_REQ_CREDIT_BUREAU_YEAR       41519
AMT_REQ_CREDIT_BUREAU_DAY        41519
AMT_REQ_CREDIT_BUREAU_QRT        41519
NAME_TYPE_SUITE                   1292
DEF_60_CNT_SOCIAL_CIRCLE          1021
OBS_60_CNT_SOCIAL_CIRCLE          1021
DEF_30_CNT_SOCIAL_CIRCLE          1021
OBS_30_CNT_SOCIAL_CIRCLE          1021
EXT_SOURCE_2                       660
AMT_GOODS_PRICE                    278
AMT_ANNUITY                         12
CNT_FAM_MEMBERS                      2
DAYS_LAST_PHONE_CHANGE               1
dtype: int64

In [146]:
(app_train.isnull().sum() > 0).sum()

np.int64(67)

In [147]:
missing_pct = (app_train.isnull().mean() * 100).sort_values(ascending=False)
missing_pct[missing_pct > 0]

COMMONAREA_AVG                 69.87
COMMONAREA_MODE                69.87
COMMONAREA_MEDI                69.87
NONLIVINGAPARTMENTS_MEDI       69.43
NONLIVINGAPARTMENTS_MODE       69.43
NONLIVINGAPARTMENTS_AVG        69.43
FONDKAPREMONT_MODE             68.39
LIVINGAPARTMENTS_AVG           68.35
LIVINGAPARTMENTS_MEDI          68.35
LIVINGAPARTMENTS_MODE          68.35
FLOORSMIN_MODE                 67.85
FLOORSMIN_AVG                  67.85
FLOORSMIN_MEDI                 67.85
YEARS_BUILD_AVG                66.50
YEARS_BUILD_MODE               66.50
YEARS_BUILD_MEDI               66.50
OWN_CAR_AGE                    65.99
LANDAREA_MEDI                  59.38
LANDAREA_AVG                   59.38
LANDAREA_MODE                  59.38
BASEMENTAREA_MODE              58.52
BASEMENTAREA_MEDI              58.52
BASEMENTAREA_AVG               58.52
EXT_SOURCE_1                   56.38
NONLIVINGAREA_MODE             55.18
NONLIVINGAREA_AVG              55.18
NONLIVINGAREA_MEDI             55.18
ELEVATORS_AVG                  53.30
ELEVATORS_MEDI                 53.30
ELEVATORS_MODE                 53.30
WALLSMATERIAL_MODE             50.84
APARTMENTS_AVG                 50.75
APARTMENTS_MEDI                50.75
APARTMENTS_MODE                50.75
ENTRANCES_MODE                 50.35
ENTRANCES_MEDI                 50.35
ENTRANCES_AVG                  50.35
LIVINGAREA_AVG                 50.19
LIVINGAREA_MEDI                50.19
LIVINGAREA_MODE                50.19
HOUSETYPE_MODE                 50.18
FLOORSMAX_MODE                 49.76
FLOORSMAX_AVG                  49.76
FLOORSMAX_MEDI                 49.76
YEARS_BEGINEXPLUATATION_MODE   48.78
YEARS_BEGINEXPLUATATION_MEDI   48.78
YEARS_BEGINEXPLUATATION_AVG    48.78
TOTALAREA_MODE                 48.27
EMERGENCYSTATE_MODE            47.40
OCCUPATION_TYPE                31.35
EXT_SOURCE_3                   19.83
AMT_REQ_CREDIT_BUREAU_HOUR     13.50
AMT_REQ_CREDIT_BUREAU_WEEK     13.50
AMT_REQ_CREDIT_BUREAU_MON      13.50
AMT_REQ_CREDIT_BUREAU_YEAR     13.50
AMT_REQ_CREDIT_BUREAU_DAY      13.50
AMT_REQ_CREDIT_BUREAU_QRT      13.50
NAME_TYPE_SUITE                 0.42
DEF_60_CNT_SOCIAL_CIRCLE        0.33
OBS_60_CNT_SOCIAL_CIRCLE        0.33
DEF_30_CNT_SOCIAL_CIRCLE        0.33
OBS_30_CNT_SOCIAL_CIRCLE        0.33
EXT_SOURCE_2                    0.21
AMT_GOODS_PRICE                 0.09
AMT_ANNUITY                     0.00
CNT_FAM_MEMBERS                 0.00
DAYS_LAST_PHONE_CHANGE          0.00
dtype: float64

In [148]:
missing = app_train.isnull().sum()
missing_pct = (missing / len(app_train) * 100).round(2)
missing_table = pd.DataFrame({
    "missing_count": missing,
    "missing_pct": missing_pct
})
missing_table

                            missing_count  missing_pct
SK_ID_CURR                              0         0.00
TARGET                                  0         0.00
NAME_CONTRACT_TYPE                      0         0.00
CODE_GENDER                             0         0.00
FLAG_OWN_CAR                            0         0.00
...                                   ...          ...
AMT_REQ_CREDIT_BUREAU_DAY           41519        13.50
AMT_REQ_CREDIT_BUREAU_WEEK          41519        13.50
AMT_REQ_CREDIT_BUREAU_MON           41519        13.50
AMT_REQ_CREDIT_BUREAU_QRT           41519        13.50
AMT_REQ_CREDIT_BUREAU_YEAR          41519        13.50

[122 rows x 2 columns]

In [149]:
missing_table = missing_table[missing_table["missing_count"] > 0]
missing_table = missing_table.sort_values("missing_pct", ascending=False)
missing_table.head(20)

                          missing_count  missing_pct
COMMONAREA_MEDI                  214865        69.87
COMMONAREA_MODE                  214865        69.87
COMMONAREA_AVG                   214865        69.87
NONLIVINGAPARTMENTS_MODE         213514        69.43
NONLIVINGAPARTMENTS_MEDI         213514        69.43
NONLIVINGAPARTMENTS_AVG          213514        69.43
FONDKAPREMONT_MODE               210295        68.39
LIVINGAPARTMENTS_AVG             210199        68.35
LIVINGAPARTMENTS_MEDI            210199        68.35
LIVINGAPARTMENTS_MODE            210199        68.35
FLOORSMIN_MEDI                   208642        67.85
FLOORSMIN_MODE                   208642        67.85
FLOORSMIN_AVG                    208642        67.85
YEARS_BUILD_MODE                 204488        66.50
YEARS_BUILD_MEDI                 204488        66.50
YEARS_BUILD_AVG                  204488        66.50
OWN_CAR_AGE                      202929        65.99
LANDAREA_AVG                     182590        59.38
LANDAREA_MEDI                    182590        59.38
LANDAREA_MODE                    182590        59.38

In [150]:
app_train["TARGET"].value_counts()

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [151]:
(app_train["TARGET"].value_counts(normalize=True) * 100).round(2)

TARGET
0   91.93
1    8.07
Name: proportion, dtype: float64

In [152]:
app_train.dtypes.value_counts()

float64    65
int64      41
str        16
Name: count, dtype: int64

In [153]:
num_cols = app_train.select_dtypes(include=["int64", "float64"]).columns
cat_cols = app_train.select_dtypes(include=["object", "string", "str"]).columns

print("Numeric:", len(num_cols))
print("Categorical:", len(cat_cols))

Numeric: 106
Categorical: 16

In [154]:
app_train[["TARGET","AMT_INCOME_TOTAL","AMT_CREDIT","EXT_SOURCE_1","EXT_SOURCE_2","EXT_SOURCE_3"]].describe()

         TARGET  AMT_INCOME_TOTAL  AMT_CREDIT  EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3
count 307511.00         307511.00   307511.00     134133.00     306851.00     246546.00
mean       0.08         168797.92   599026.00          0.50          0.51          0.51
std        0.27         237123.15   402490.78          0.21          0.19          0.19
min        0.00          25650.00    45000.00          0.01          0.00          0.00
25%        0.00         112500.00   270000.00          0.33          0.39          0.37
50%        0.00         147150.00   513531.00          0.51          0.57          0.54
75%        0.00         202500.00   808650.00          0.68          0.66          0.67
max        1.00      117000000.00  4050000.00          0.96          0.85          0.90

In [155]:
app_train.groupby("TARGET")[["AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED"]].median()

        AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  DAYS_BIRTH  DAYS_EMPLOYED
TARGET
0              148500.00   517788.00     24876.00   -15877.00       -1235.00
1              135000.00   497520.00     25263.00   -14282.00       -1034.00

In [156]:
app_train.groupby("TARGET")[[
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3"
]].mean()

        EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3
TARGET
0               0.51          0.52          0.52
1               0.39          0.41          0.39

In [243]:
app_train["EXT_SOURCE_MEAN"] = app_train[
    ["EXT_SOURCE_1","EXT_SOURCE_2","EXT_SOURCE_3"]
].mean(axis=1)

app_train["EXT_SOURCE_MIN"] = app_train[
    ["EXT_SOURCE_1","EXT_SOURCE_2","EXT_SOURCE_3"]
].min(axis=1)

app_train["EXT_SOURCE_MAX"] = app_train[
    ["EXT_SOURCE_1","EXT_SOURCE_2","EXT_SOURCE_3"]
].max(axis=1)

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4261419566.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EXT_SOURCE_MEAN"] = app_train[
C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4261419566.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EXT_SOURCE_MIN"] = app_train[
C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4261419566.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EXT_SOURCE_MAX"] = app_train[

In [158]:
app_train.groupby("TARGET")[["EXT_SOURCE_MEAN"]].mean()

        EXT_SOURCE_MEAN
TARGET
0                  0.52
1                  0.40

In [244]:
app_train["CREDIT_INCOME_RATIO"] = app_train["AMT_CREDIT"] / app_train["AMT_INCOME_TOTAL"]

app_train["ANNUITY_INCOME_RATIO"] = app_train["AMT_ANNUITY"] / app_train["AMT_INCOME_TOTAL"]

app_train["AGE_YEARS"] = abs(app_train["DAYS_BIRTH"]) / 365

app_train["EMPLOYED_YEARS"] = abs(app_train["DAYS_EMPLOYED"]) / 365

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4011920644.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["CREDIT_INCOME_RATIO"] = app_train["AMT_CREDIT"] / app_train["AMT_INCOME_TOTAL"]
C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4011920644.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["ANNUITY_INCOME_RATIO"] = app_train["AMT_ANNUITY"] / app_train["AMT_INCOME_TOTAL"]
C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4011920644.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["AGE_YEARS"] = abs(app_train["DAYS_BIRTH"]) / 365
C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4011920644.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EMPLOYED_YEARS"] = abs(app_train["DAYS_EMPLOYED"]) / 365

In [160]:
app_train.groupby("TARGET")[[
    "CREDIT_INCOME_RATIO",
    "ANNUITY_INCOME_RATIO",
    "AGE_YEARS",
    "EMPLOYED_YEARS"
]].median()

        CREDIT_INCOME_RATIO  ANNUITY_INCOME_RATIO  AGE_YEARS  EMPLOYED_YEARS
TARGET
0                      3.27                  0.16      43.50            6.31
1                      3.25                  0.17      39.13            3.99

In [161]:
app_train["DAYS_EMPLOYED"].describe()

count   307511.00
mean     63815.05
std     141275.77
min     -17912.00
25%      -2760.00
50%      -1213.00
75%       -289.00
max     365243.00
Name: DAYS_EMPLOYED, dtype: float64

In [162]:
(app_train["DAYS_EMPLOYED"] == 365243).sum()

np.int64(55374)

In [245]:
app_train["DAYS_EMPLOYED"] = app_train["DAYS_EMPLOYED"].replace(365243, np.nan)

In [164]:
app_train["DAYS_EMPLOYED"].isnull().sum()

np.int64(55374)

In [246]:
app_train["EMPLOYED_ANOMALY"] = app_train["DAYS_EMPLOYED"].isnull().astype(int)

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\783279822.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EMPLOYED_ANOMALY"] = app_train["DAYS_EMPLOYED"].isnull().astype(int)

In [166]:
app_train.groupby("TARGET")["EMPLOYED_ANOMALY"].mean()

TARGET
0   0.19
1   0.12
Name: EMPLOYED_ANOMALY, dtype: float64

In [167]:
missing_table.head(15)

                          missing_count  missing_pct
COMMONAREA_MEDI                  214865        69.87
COMMONAREA_MODE                  214865        69.87
COMMONAREA_AVG                   214865        69.87
NONLIVINGAPARTMENTS_MODE         213514        69.43
NONLIVINGAPARTMENTS_MEDI         213514        69.43
NONLIVINGAPARTMENTS_AVG          213514        69.43
FONDKAPREMONT_MODE               210295        68.39
LIVINGAPARTMENTS_AVG             210199        68.35
LIVINGAPARTMENTS_MEDI            210199        68.35
LIVINGAPARTMENTS_MODE            210199        68.35
FLOORSMIN_MEDI                   208642        67.85
FLOORSMIN_MODE                   208642        67.85
FLOORSMIN_AVG                    208642        67.85
YEARS_BUILD_MODE                 204488        66.50
YEARS_BUILD_MEDI                 204488        66.50

In [247]:
high_missing_cols = missing_table[missing_table["missing_pct"] > 65].index

app_train.drop(columns=high_missing_cols, inplace=True)

In [248]:
app_train.shape

(307511, 113)

In [170]:
num_cols = app_train.select_dtypes(include=["float64","int64"]).columns
cat_cols = app_train.select_dtypes(include=["object"]).columns

len(num_cols), len(cat_cols)

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\4138885195.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = app_train.select_dtypes(include=["object"]).columns

(98, 15)

In [171]:
from sklearn.impute import SimpleImputer

num_imputer = SimpleImputer(strategy="median")

In [172]:
cat_imputer = SimpleImputer(strategy="most_frequent")

In [173]:
app_train.isnull().sum().sort_values(ascending=False).head(10)

LANDAREA_AVG          182590
LANDAREA_MODE         182590
LANDAREA_MEDI         182590
BASEMENTAREA_MEDI     179943
BASEMENTAREA_MODE     179943
BASEMENTAREA_AVG      179943
EXT_SOURCE_1          173378
NONLIVINGAREA_AVG     169682
NONLIVINGAREA_MEDI    169682
NONLIVINGAREA_MODE    169682
dtype: int64

In [174]:
X = app_train.drop(columns=["TARGET"])
y = app_train["TARGET"]

In [175]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [176]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

In [177]:
num_cols = X.select_dtypes(include=["float64","int64"]).columns
cat_cols = X.select_dtypes(include=["object", "string"]).columns

In [178]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression

In [179]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

In [180]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [181]:
preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [182]:
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [183]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
model.fit(X_train, y_train)

d:\Projects\credit-risk-default-prediction\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       'DAYS_ID_PUBLISH', 'FLAG_MOBIL', 'FLAG_E...
                                                  Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [185]:
from sklearn.preprocessing import StandardScaler

In [186]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [187]:
preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [188]:
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [ ]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       'DAYS_ID_P...
                                                  Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [190]:
from sklearn.metrics import roc_auc_score

y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7486219162564851

In [191]:
from sklearn.ensemble import RandomForestClassifier

model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", RandomForestClassifier(n_estimators=100, random_state=42))
])

In [192]:
model.fit(X_train, y_train)

y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc_score(y_valid, y_pred_proba)

0.7173477795700114

In [193]:
from sklearn.ensemble import RandomForestClassifier

model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        min_samples_split=20,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

In [ ]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       'DAYS_ID_P...
                                                  Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str'))])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=10,
                                        min_samples_split=20, n_estimators=300,
                                        n_jobs=-1, random_state=42))])

In [195]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc_score(y_valid, y_pred_proba)

0.7438802631188491

In [196]:
pip install xgboost

Requirement already satisfied: xgboost in d:\projects\credit-risk-default-prediction\venv\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in d:\projects\credit-risk-default-prediction\venv\lib\site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in d:\projects\credit-risk-default-prediction\venv\lib\site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [197]:
from xgboost import XGBClassifier

In [198]:
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight= (len(y_train) - sum(y_train)) / sum(y_train),
        random_state=42,
        n_jobs=-1,
        eval_metric="logloss"
    ))
])

In [199]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       'DAYS_ID_P...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [200]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7598159631481711

In [201]:
print(type(model.named_steps["classifier"]))

<class 'xgboost.sklearn.XGBClassifier'>

In [202]:
import pandas as pd

feature_names = model.named_steps["preprocessing"].get_feature_names_out()
importances = model.named_steps["classifier"].feature_importances_

feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

feat_imp.head(20)

                                               feature  importance
89                                num__EXT_SOURCE_MEAN        0.05
90                                 num__EXT_SOURCE_MIN        0.02
122          cat__NAME_EDUCATION_TYPE_Higher education        0.02
91                                 num__EXT_SOURCE_MAX        0.01
100                                 cat__CODE_GENDER_M        0.01
125  cat__NAME_EDUCATION_TYPE_Secondary / secondary...        0.01
99                                  cat__CODE_GENDER_F        0.01
116                    cat__NAME_INCOME_TYPE_Pensioner        0.01
103                                cat__FLAG_OWN_CAR_Y        0.01
97                  cat__NAME_CONTRACT_TYPE_Cash loans        0.01
95                                 num__EMPLOYED_YEARS        0.01
64                                num__FLAG_DOCUMENT_3        0.01
102                                cat__FLAG_OWN_CAR_N        0.01
29                                   num__EXT_SOURCE_3        0.01
127                    cat__NAME_FAMILY_STATUS_Married        0.01
98             cat__NAME_CONTRACT_TYPE_Revolving loans        0.01
24                         num__REG_CITY_NOT_LIVE_CITY        0.01
5                                 num__AMT_GOODS_PRICE        0.01
61                       num__DEF_60_CNT_SOCIAL_CIRCLE        0.01
19                    num__REGION_RATING_CLIENT_W_CITY        0.01

In [249]:
app_train["EXT_SOURCE_STD"] = app_train[[
    "EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"
]].std(axis=1)

app_train["EXT_SOURCE_PROD"] = (
    app_train["EXT_SOURCE_1"] *
    app_train["EXT_SOURCE_2"] *
    app_train["EXT_SOURCE_3"]
)

In [250]:
app_train["CREDIT_PER_PERSON"] = (
    app_train["AMT_CREDIT"] / app_train["CNT_FAM_MEMBERS"]
)

app_train["INCOME_PER_PERSON"] = (
    app_train["AMT_INCOME_TOTAL"] / app_train["CNT_FAM_MEMBERS"]
)

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\269671912.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["CREDIT_PER_PERSON"] = (
C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\269671912.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["INCOME_PER_PERSON"] = (

In [251]:
app_train["EMPLOYED_AGE_RATIO"] = (
    app_train["EMPLOYED_YEARS"] / app_train["AGE_YEARS"]
)

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\1295828519.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EMPLOYED_AGE_RATIO"] = (

In [252]:
app_train["EXT_SOURCE_INCOME"] = (
    app_train["EXT_SOURCE_MEAN"] * app_train["AMT_INCOME_TOTAL"]
)

C:\Users\sanid\AppData\Local\Temp\ipykernel_11916\2607188164.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train["EXT_SOURCE_INCOME"] = (

In [253]:
app_train_final = app_train.copy()

In [322]:
X = app_train.drop("TARGET", axis=1)
y = app_train["TARGET"]

In [323]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [324]:
num_cols = X.select_dtypes(include=["float64","int64"]).columns
cat_cols = X.select_dtypes(include=["object", "string"]).columns

In [325]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [326]:
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight= (len(y_train) - sum(y_train)) / sum(y_train),
        random_state=42,
        n_jobs=-1,
        eval_metric="logloss"
    ))
])

In [224]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       ...
       'ANNUIT...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [226]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7605311733765351

In [216]:
print("EXT_SOURCE_PROD" in X.columns)
print("EMPLOYED_AGE_RATIO" in X.columns)

True
True

In [227]:
feature_names = model.named_steps["preprocessing"].get_feature_names_out()

print([f for f in feature_names if "EXT_SOURCE_PROD" in f])

['num__EXT_SOURCE_PROD']

In [254]:
bureau = pd.read_csv(r"D:\Projects\credit-risk-default-prediction\data\raw\bureau.csv")

In [255]:
bureau_agg = bureau.groupby("SK_ID_CURR").agg({
    "AMT_CREDIT_SUM": "sum",
    "AMT_CREDIT_SUM_DEBT": "sum",
    "AMT_CREDIT_SUM_OVERDUE": "sum",
    "DAYS_CREDIT": "mean"
}).reset_index()

In [256]:
bureau_agg["DEBT_CREDIT_RATIO"] = (
    bureau_agg["AMT_CREDIT_SUM_DEBT"] / bureau_agg["AMT_CREDIT_SUM"]
)

bureau_agg["OVERDUE_RATIO"] = (
    bureau_agg["AMT_CREDIT_SUM_OVERDUE"] / bureau_agg["AMT_CREDIT_SUM"]
)

In [257]:
app_train = app_train.merge(bureau_agg, on="SK_ID_CURR", how="left")

In [264]:
pip install pyarrow==15.0.2

^C
Note: you may need to restart the kernel to use updated packages.

Collecting pyarrow==15.0.2
  Downloading pyarrow-15.0.2-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Collecting numpy<2,>=1.16.6 (from pyarrow==15.0.2)
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 806.3 kB/s eta 0:00:00
Downloading pyarrow-15.0.2-cp312-cp312-win_amd64.whl (25.3 MB)
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/25.3 MB 2.2 MB/s eta 0:00:12
   ---------------------------------------- 0.2/25.3 MB 1.7 MB/s eta 0:00:15
   ---------------------------------------- 0.2/25.3 MB 1.7 MB/s eta 0:00:15
   ---------------------------------------- 0.3/25.3 MB 1.8 MB/s eta 0:00:15
    --------------------------------------- 0.4/25.3 MB 1.8 MB/s eta 0:00:15
    --------------------------------------- 0.5/25.3 MB 1.7 MB/s eta 0:00:15
    --------------------------------------- 0.6/25.3 MB 1.8 MB/s eta 0:00:14
    --------------------------------------- 0.6/25.3 MB 1.8 MB/s eta 0:00:14
   - -------------------------------------- 0.7/25.3 MB 1.6 MB/s eta 0:00:16
   - -------------------------------------- 0.7/25.3 MB 1.6 MB/s eta 0:00:16
   - -------------------------------------- 0.7/25.3 MB 1.4 MB/s eta 0:00:18
   - -------------------------------------- 0.8/25.3 MB 1.5 MB/s eta 0:00:17
   - -------------------------------------- 1.0/25.3 MB 1.7 MB/s eta 0:00:15
   - -------------------------------------- 1.1/25.3 MB 1.7 MB/s eta 0:00:15
   - -------------------------------------- 1.2/25.3 MB 1.8 MB/s eta 0:00:14
   -- ------------------------------------- 1.4/25.3 MB 1.8 MB/s eta 0:00:14
   -- ------------------------------------- 1.5/25.3 MB 1.9 MB/s eta 0:00:13
   -- ------------------------------------- 1.5/25.3 MB 1.9 MB/s eta 0:00:13
   -- ------------------------------------- 1.7/25.3 MB 1.9 MB/s eta 0:00:13
   -- ------------------------------------- 1.8/25.3 MB 1.9 MB/s eta 0:00:13
   --- ------------------------------------ 1.9/25.3 MB 1.9 MB/s eta 0:00:13
   --- ------------------------------------ 2.0/25.3 MB 2.0 MB/s eta 0:00:12
   --- ------------------------------------ 2.2/25.3 MB 2.1 MB/s eta 0:00:12
   --- ------------------------------------ 2.2/25.3 MB 2.1 MB/s eta 0:00:12
   --- ------------------------------------ 2.4/25.3 MB 2.1 MB/s eta 0:00:12
   --- ------------------------------------ 2.4/25.3 MB 2.1 MB/s eta 0:00:11
   ---- ----------------------------------- 2.7/25.3 MB 2.1 MB/s eta 0:00:11
   ---- ----------------------------------- 2.8/25.3 MB 2.1 MB/s eta 0:00:11
   ---- ----------------------------------- 2.8/25.3 MB 2.1 MB/s eta 0:00:11
   ---- ----------------------------------- 3.1/25.3 MB 2.2 MB/s eta 0:00:11
   ----- ---------------------------------- 3.2/25.3 MB 2.2 MB/s eta 0:00:10
   ----- ---------------------------------- 3.2/25.3 MB 2.2 MB/s eta 0:00:10
   ----- ---------------------------------- 3.2/25.3 MB 2.2 MB/s eta 0:00:11
   ----- ---------------------------------- 3.4/25.3 MB 2.2 MB/s eta 0:00:11
   ----- ---------------------------------- 3.4/25.3 MB 2.2 MB/s eta 0:00:11
   ----- ---------------------------------- 3.5/25.3 MB 2.1 MB/s eta 0:00:11
   ----- ---------------------------------- 3.7/25.3 MB 2.2 MB/s eta 0:00:10
   ----- ---------------------------------- 3.8/25.3 MB 2.2 MB/s eta 0:00:10
   ------ --------------------------------- 4.0/25.3 MB 2.2 MB/s eta 0:00:10
   ------ --------------------------------- 4.0/25.3 MB 2.2 MB/s eta 0:00:10
   ------ --------------------------------- 4.2/25.3 MB 2.2 MB/s eta 0:00:10
   ------ --------------------------------- 4.2/25.3 MB 2.2 MB/s eta 0:00:10
   ------ --------------------------------- 4.4/25.3 MB 2.2 MB/s eta 0:00:10
   ------- -------------------------------- 4.6/25.3 MB 2.3 MB/s eta 0:00:10
   ------- -------------------------------- 4.6/25.3 MB 2.2 MB/s eta 0:00:10
   ------- -------------------------------- 4.8/25.3 MB 2.3 MB/s eta 0:00:09
   ------- -------------------------------- 5.0/25.3 MB 2.3 MB/s eta 0:00:09
   -------- ------------------------------- 5.1/25.3 MB 2.3 MB/s eta 0:00:09
   -------- ------------------------------- 5.3/25.3 MB 2.4 MB/s eta 0:00:09
   -------- ------------------------------- 5.4/25.3 MB 2.4 MB/s eta 0:00:09
   -------- ------------------------------- 5.5/25.3 MB 2.4 MB/s eta 0:00:09
   -------- ------------------------------- 5.7/25.3 MB 2.4 MB/s eta 0:00:09
   --------- ------------------------------ 5.8/25.3 MB 2.4 MB/s eta 0:00:08
   --------- ------------------------------ 5.9/25.3 MB 2.4 MB/s eta 0:00:08
   --------- ------------------------------ 5.9/25.3 MB 2.4 MB/s eta 0:00:09
   --------- ------------------------------ 6.1/25.3 MB 2.5 MB/s eta 0:00:08
   --------- ------------------------------ 6.3/25.3 MB 2.5 MB/s eta 0:00:08
   --------- ------------------------------ 6.3/25.3 MB 2.4 MB/s eta 0:00:08
   ---------- ----------------------------- 6.4/25.3 MB 2.5 MB/s eta 0:00:08
   ---------- ----------------------------- 6.4/25.3 MB 2.4 MB/s eta 0:00:08
   ---------- ----------------------------- 6.7/25.3 MB 2.5 MB/s eta 0:00:08
   ---------- ----------------------------- 6.8/25.3 MB 2.5 MB/s eta 0:00:08
   ---------- ----------------------------- 6.8/25.3 MB 2.5 MB/s eta 0:00:08
   ----------- ---------------------------- 7.0/25.3 MB 2.5 MB/s eta 0:00:08
   ----------- ---------------------------- 7.1/25.3 MB 2.5 MB/s eta 0:00:08
   ----------- ---------------------------- 7.2/25.3 MB 2.5 MB/s eta 0:00:08
   ----------- ---------------------------- 7.3/25.3 MB 2.5 MB/s eta 0:00:08
   ----------- ---------------------------- 7.5/25.3 MB 2.5 MB/s eta 0:00:08
   ------------ --------------------------- 7.7/25.3 MB 2.5 MB/s eta 0:00:07
   ------------ --------------------------- 7.7/25.3 MB 2.5 MB/s eta 0:00:07
   ------------ --------------------------- 7.9/25.3 MB 2.5 MB/s eta 0:00:07
   ------------ --------------------------- 8.1/25.3 MB 2.6 MB/s eta 0:00:07
   ------------ --------------------------- 8.2/25.3 MB 2.6 MB/s eta 0:00:07
   ------------- -------------------------- 8.3/25.3 MB 2.6 MB/s eta 0:00:07
   ------------- -------------------------- 8.6/25.3 MB 2.6 MB/s eta 0:00:07
   ------------- -------------------------- 8.7/25.3 MB 2.6 MB/s eta 0:00:07
   ------------- -------------------------- 8.8/25.3 MB 2.6 MB/s eta 0:00:07
   -------------- ------------------------- 9.1/25.3 MB 2.6 MB/s eta 0:00:07
   -------------- ------------------------- 9.3/25.3 MB 2.7 MB/s eta 0:00:06
   -------------- ------------------------- 9.3/25.3 MB 2.6 MB/s eta 0:00:07
   --------------- ------------------------ 9.6/25.3 MB 2.7 MB/s eta 0:00:06
   --------------- ------------------------ 9.7/25.3 MB 2.7 MB/s eta 0:00:06
   --------------- ------------------------ 9.8/25.3 MB 2.7 MB/s eta 0:00:06
   --------------- ------------------------ 10.0/25.3 MB 2.7 MB/s eta 0:00:06
   --------------- ------------------------ 10.0/25.3 MB 2.7 MB/s eta 0:00:06
   ---------------- ----------------------- 10.3/25.3 MB 2.7 MB/s eta 0:00:06
   ---------------- ----------------------- 10.3/25.3 MB 2.7 MB/s eta 0:00:06
   ---------------- ----------------------- 10.5/25.3 MB 2.7 MB/s eta 0:00:06
   ----------------- ---------------------- 10.8/25.3 MB 2.8 MB/s eta 0:00:06
   ----------------- ---------------------- 11.0/25.3 MB 2.9 MB/s eta 0:00:05
   ----------------- ---------------------- 11.1/25.3 MB 3.0 MB/s eta 0:00:05
   ----------------- ---------------------- 11.3/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------ --------------------- 11.4/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------ --------------------- 11.5/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------ --------------------- 11.8/25.3 MB 3.1 MB/s eta 0:00:05
   ------------------ --------------------- 11.9/25.3 MB 3.1 MB/s eta 0:00:05
   ------------------- -------------------- 12.0/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------- -------------------- 12.2/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------- -------------------- 12.2/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------- -------------------- 12.5/25.3 MB 3.0 MB/s eta 0:00:05
   ------------------- -------------------- 12.6/25.3 MB 3.1 MB/s eta 0:00:05
   -------------------- ------------------- 12.8/25.3 MB 3.1 MB/s eta 0:00:05
   -------------------- ------------------- 12.9/25.3 MB 3.1 MB/s eta 0:00:04
   -------------------- ------------------- 13.1/25.3 MB 3.1 MB/s eta 0:00:04
   -------------------- ------------------- 13.2/25.3 MB 3.1 MB/s eta 0:00:04
   --------------------- ------------------ 13.3/25.3 MB 3.1 MB/s eta 0:00:04
   --------------------- ------------------ 13.6/25.3 MB 3.2 MB/s eta 0:00:04
   --------------------- ------------------ 13.7/25.3 MB 3.3 MB/s eta 0:00:04
   --------------------- ------------------ 13.7/25.3 MB 3.2 MB/s eta 0:00:04
   --------------------- ------------------ 13.9/25.3 MB 3.2 MB/s eta 0:00:04
   ---------------------- ----------------- 13.9/25.3 MB 3.1 MB/s eta 0:00:04
   ---------------------- ----------------- 14.2/25.3 MB 3.2 MB/s eta 0:00:04
   ---------------------- ----------------- 14.3/25.3 MB 3.2 MB/s eta 0:00:04
   ---------------------- ----------------- 14.4/25.3 MB 3.2 MB/s eta 0:00:04
   ----------------------- ---------------- 14.5/25.3 MB 3.2 MB/s eta 0:00:04
   ----------------------- ---------------- 14.8/25.3 MB 3.3 MB/s eta 0:00:04
   ----------------------- ---------------- 15.0/25.3 MB 3.3 MB/s eta 0:00:04
   ----------------------- ---------------- 15.0/25.3 MB 3.3 MB/s eta 0:00:04
   ------------------------ --------------- 15.2/25.3 MB 3.3 MB/s eta 0:00:04
   ------------------------ --------------- 15.3/25.3 MB 3.2 MB/s eta 0:00:04
   ------------------------ --------------- 15.4/25.3 MB 3.2 MB/s eta 0:00:04
   ------------------------ --------------- 15.6/25.3 MB 3.3 MB/s eta 0:00:03
   ------------------------ --------------- 15.7/25.3 MB 3.2 MB/s eta 0:00:03
   ------------------------- -------------- 16.0/25.3 MB 3.3 MB/s eta 0:00:03
   ------------------------- -------------- 16.1/25.3 MB 3.3 MB/s eta 0:00:03
   ------------------------- -------------- 16.3/25.3 MB 3.3 MB/s eta 0:00:03
   -------------------------- ------------- 16.5/25.3 MB 3.4 MB/s eta 0:00:03
   -------------------------- ------------- 16.8/25.3 MB 3.4 MB/s eta 0:00:03
   -------------------------- ------------- 16.8/25.3 MB 3.4 MB/s eta 0:00:03
   -------------------------- ------------- 17.1/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.2/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.2/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.3/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.3/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.3/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.3/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.3/25.3 MB 3.4 MB/s eta 0:00:03
   --------------------------- ------------ 17.5/25.3 MB 3.2 MB/s eta 0:00:03
   --------------------------- ------------ 17.7/25.3 MB 3.2 MB/s eta 0:00:03
   ---------------------------- ----------- 17.8/25.3 MB 3.3 MB/s eta 0:00:03
   ---------------------------- ----------- 18.1/25.3 MB 3.3 MB/s eta 0:00:03
   ---------------------------- ----------- 18.3/25.3 MB 3.3 MB/s eta 0:00:03
   ----------------------------- ---------- 18.4/25.3 MB 3.3 MB/s eta 0:00:03
   ----------------------------- ---------- 18.5/25.3 MB 3.3 MB/s eta 0:00:03
   ----------------------------- ---------- 18.6/25.3 MB 3.3 MB/s eta 0:00:03
   ----------------------------- ---------- 18.8/25.3 MB 3.3 MB/s eta 0:00:02
   ----------------------------- ---------- 18.9/25.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------ --------- 19.2/25.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------ --------- 19.4/25.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------- -------- 19.7/25.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------- -------- 19.9/25.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------- -------- 20.1/25.3 MB 3.4 MB/s eta 0:00:02
   ------------------------------- -------- 20.1/25.3 MB 3.4 MB/s eta 0:00:02
   -------------------------------- ------- 20.4/25.3 MB 3.4 MB/s eta 0:00:02
   -------------------------------- ------- 20.5/25.3 MB 3.4 MB/s eta 0:00:02
   -------------------------------- ------- 20.6/25.3 MB 3.4 MB/s eta 0:00:02
   -------------------------------- ------- 20.7/25.3 MB 3.4 MB/s eta 0:00:02
   -------------------------------- ------- 20.8/25.3 MB 3.4 MB/s eta 0:00:02
   --------------------------------- ------ 21.1/25.3 MB 3.4 MB/s eta 0:00:02
   --------------------------------- ------ 21.2/25.3 MB 3.4 MB/s eta 0:00:02
   --------------------------------- ------ 21.4/25.3 MB 3.4 MB/s eta 0:00:02
   --------------------------------- ------ 21.4/25.3 MB 3.3 MB/s eta 0:00:02
   ---------------------------------- ----- 21.6/25.3 MB 3.4 MB/s eta 0:00:02
   ---------------------------------- ----- 21.9/25.3 MB 3.4 MB/s eta 0:00:02
   ---------------------------------- ----- 21.9/25.3 MB 3.4 MB/s eta 0:00:02
   ---------------------------------- ----- 22.0/25.3 MB 3.3 MB/s eta 0:00:01
   ----------------------------------- ---- 22.2/25.3 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 22.3/25.3 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 22.6/25.3 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 22.6/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 22.8/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 23.0/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 23.2/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 23.2/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 23.5/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 23.6/25.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 23.8/25.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------- -- 23.9/25.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------- -- 23.9/25.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 24.1/25.3 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 24.4/25.3 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 24.6/25.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  24.7/25.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  25.0/25.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  25.3/25.3 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 25.3/25.3 MB 3.4 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 3.8 MB/s eta 0:00:05
    --------------------------------------- 0.2/15.5 MB 4.6 MB/s eta 0:00:04
    --------------------------------------- 0.2/15.5 MB 4.6 MB/s eta 0:00:04
    --------------------------------------- 0.3/15.5 MB 2.1 MB/s eta 0:00:08
   - -------------------------------------- 0.5/15.5 MB 2.3 MB/s eta 0:00:07
   - -------------------------------------- 0.8/15.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 0.9/15.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/15.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/15.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/15.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/15.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.1/15.5 MB 2.1 MB/s eta 0:00:07
   --- ------------------------------------ 1.3/15.5 MB 2.3 MB/s eta 0:00:07
   ----- ---------------------------------- 2.0/15.5 MB 3.2 MB/s eta 0:00:05
   ----- ---------------------------------- 2.2/15.5 MB 3.3 MB/s eta 0:00:05
   ----- ---------------------------------- 2.3/15.5 MB 3.2 MB/s eta 0:00:05
   ------ --------------------------------- 2.5/15.5 MB 3.3 MB/s eta 0:00:04
   ------ --------------------------------- 2.5/15.5 MB 3.3 MB/s eta 0:00:04
   ------ --------------------------------- 2.6/15.5 MB 3.1 MB/s eta 0:00:05
   ------ --------------------------------- 2.7/15.5 MB 3.0 MB/s eta 0:00:05
   ------- -------------------------------- 3.0/15.5 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 3.1/15.5 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 3.2/15.5 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 3.3/15.5 MB 3.2 MB/s eta 0:00:04
   --------- ------------------------------ 3.5/15.5 MB 3.2 MB/s eta 0:00:04
   --------- ------------------------------ 3.7/15.5 MB 3.3 MB/s eta 0:00:04
   ---------- ----------------------------- 3.9/15.5 MB 3.3 MB/s eta 0:00:04
   ---------- ----------------------------- 3.9/15.5 MB 3.3 MB/s eta 0:00:04
   ---------- ----------------------------- 4.0/15.5 MB 3.2 MB/s eta 0:00:04
   ---------- ----------------------------- 4.2/15.5 MB 3.3 MB/s eta 0:00:04
   ----------- ---------------------------- 4.4/15.5 MB 3.3 MB/s eta 0:00:04
   ----------- ---------------------------- 4.5/15.5 MB 3.3 MB/s eta 0:00:04
   ----------- ---------------------------- 4.5/15.5 MB 3.3 MB/s eta 0:00:04
   ------------ --------------------------- 4.7/15.5 MB 3.2 MB/s eta 0:00:04
   ------------ --------------------------- 4.9/15.5 MB 3.2 MB/s eta 0:00:04
   ------------- -------------------------- 5.1/15.5 MB 3.3 MB/s eta 0:00:04
   ------------- -------------------------- 5.2/15.5 MB 3.3 MB/s eta 0:00:04
   ------------- -------------------------- 5.3/15.5 MB 3.2 MB/s eta 0:00:04
   -------------- ------------------------- 5.6/15.5 MB 3.3 MB/s eta 0:00:04
   -------------- ------------------------- 5.6/15.5 MB 3.2 MB/s eta 0:00:04
   -------------- ------------------------- 5.8/15.5 MB 3.2 MB/s eta 0:00:03
   --------------- ------------------------ 5.9/15.5 MB 3.2 MB/s eta 0:00:03
   --------------- ------------------------ 6.0/15.5 MB 3.2 MB/s eta 0:00:03
   ---------------- ----------------------- 6.3/15.5 MB 3.3 MB/s eta 0:00:03
   ---------------- ----------------------- 6.5/15.5 MB 3.3 MB/s eta 0:00:03
   ---------------- ----------------------- 6.5/15.5 MB 3.3 MB/s eta 0:00:03
   ----------------- ---------------------- 6.7/15.5 MB 3.3 MB/s eta 0:00:03
   ----------------- ---------------------- 6.9/15.5 MB 3.3 MB/s eta 0:00:03
   ------------------ --------------------- 7.1/15.5 MB 3.4 MB/s eta 0:00:03
   ------------------- -------------------- 7.5/15.5 MB 3.5 MB/s eta 0:00:03
   ------------------- -------------------- 7.7/15.5 MB 3.5 MB/s eta 0:00:03
   ------------------- -------------------- 7.7/15.5 MB 3.4 MB/s eta 0:00:03
   ------------------- -------------------- 7.7/15.5 MB 3.4 MB/s eta 0:00:03
   ------------------- -------------------- 7.7/15.5 MB 3.4 MB/s eta 0:00:03
   -------------------- ------------------- 7.9/15.5 MB 3.3 MB/s eta 0:00:03
   -------------------- ------------------- 8.1/15.5 MB 3.3 MB/s eta 0:00:03
   --------------------- ------------------ 8.3/15.5 MB 3.4 MB/s eta 0:00:03
   ---------------------- ----------------- 8.6/15.5 MB 3.4 MB/s eta 0:00:03
   ---------------------- ----------------- 8.8/15.5 MB 3.4 MB/s eta 0:00:02

  WARNING: Failed to remove contents in a temporary directory 'D:\Projects\credit-risk-default-prediction\venv\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Projects\credit-risk-default-prediction\venv\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Projects\credit-risk-default-prediction\venv\Lib\site-packages\~yarrow.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\Projects\credit-risk-default-prediction\venv\Lib\site-packages\~yarrow'.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [266]:
app_train.to_parquet("app_train_fe.parquet")

ArrowKeyError: A type extension with name pandas.period already defined

In [267]:
app_train.to_pickle("app_train_fe.pkl")

In [ ]:
# app_train = pd.read_pickle("app_train_fe.pkl")

In [279]:
X = app_train.drop("TARGET", axis=1)
y = app_train["TARGET"]

In [280]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [281]:
num_cols = X.select_dtypes(include=["float64","int64"]).columns
cat_cols = X.select_dtypes(include=["object", "string"]).columns

In [305]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [306]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [307]:
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight= (len(y_train) - sum(y_train)) / sum(y_train),
        random_state=42,
        n_jobs=-1,
        eval_metric="logloss"
    ))
])

In [274]:
model.fit(X_train, y_train)

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [299]:
import numpy as np

np.isinf(app_train.select_dtypes(include=np.number)).sum().sum()

np.int64(0)

In [276]:
app_train.replace([np.inf, -np.inf], np.nan, inplace=True)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_MEAN,EXT_SOURCE_MIN,EXT_SOURCE_MAX,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,AGE_YEARS,EMPLOYED_YEARS,EMPLOYED_ANOMALY,EXT_SOURCE_STD,EXT_SOURCE_PROD,CREDIT_PER_PERSON,INCOME_PER_PERSON,EMPLOYED_AGE_RATIO,EXT_SOURCE_INCOME,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT,DEBT_CREDIT_RATIO,OVERDUE_RATIO
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637.00,-3648.00,-2120,1,1,0,1,1,0,Laborers,1.00,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.08,0.26,0.14,0.02,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,block of flats,0.01,"Stone, brick",No,2.00,2.00,2.00,2.00,-1134.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00,0.16,0.08,0.26,2.01,0.12,25.92,1.75,0,0.09,0.00,406597.50,202500.00,0.07,32761.89,865055.56,245781.00,0.00,-874.00,0.28,0.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188.00,-1186.00,-291,1,1,0,1,1,0,Core staff,2.00,1,1,MONDAY,11,0,0,0,0,0,0,School,0.31,0.62,NaN,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.05,0.01,0.09,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.00,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.01,block of flats,0.07,Block,No,1.00,0.00,1.00,0.00,-828.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.47,0.31,0.62,4.79,0.13,45.93,3.25,0,0.22,NaN,646751.25,135000.00,0.07,126024.27,1017400.50,0.00,0.00,-1400.75,0.00,0.00
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225.00,-4260.00,-2531,1,1,1,1,1,0,Laborers,1.00,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.56,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-815.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.64,0.56,0.73,2.00,0.10,52.18,0.62,0,0.12,NaN,135000.00,67500.00,0.01,43384.91,189037.80,0.00,0.00,-867.00,0.00,0.00
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039.00,-9833.00,-2437,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.00,2.00,0.00,-617.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.65,0.65,0.65,2.32,0.22,52.07,8.33,0,NaN,NaN,156341.25,67500.00,0.16,87809.63,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038.00,-4311.00,-3458,1,1,0,1,0,0,Core staff,1.00,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-1106.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.32,0.32,0.32,4.22,0.18,54.61,8.32,0,NaN,NaN,513000.00,121500.00,0.15,39212.70,146250.00,0.00,0.00,-1149.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.00,254700.00,27558.00,225000.00,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.03,-9327,-236.00,-8456.00,-1982,1,1,0,1,0,0,Sales staff,1.00,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.15,0.68,NaN,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,0.10,0.02,0.98,0.08,0.03,0.46,0.01,0.09,0.01,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,block of flats,0.29,"Stone, brick",No,0.00,0.00,0.00,0.00,-273.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.41,0.15,0.68,1.62,0.17,25.55,0.65,0,0.38,NaN,254700.00,157500.00,0.03,65142.22,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.00,269550.00,12001.50,225000.00,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.03,-20775,NaN,-4388.00,-4090,1,0,0,1,1,0,NaN,1.00,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.12,NaN,0.02,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.05,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,block of flats,0.02,"Stone, brick",No,0.00,0.00,0.00,0.00,0.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.12,0.12,0.12,3.74,0.17,56.92,1000.67,1,NaN,NaN,269550.00,72000.00,17.58,8351.43,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.00,677664.00,29979.00,585000.00,Unaccompanied,Working,Higher education,Separated,House / apartment,0.01,-14966,-7921.00,-6737.00,-5150,1,1,0,1,0,1,Managers,1.00,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.74,0.54,0.22,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.93,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.97,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.94,0.00,block of flats,0.80,Panel,No,6.00,0.00,6.00,0.00,-1909.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.00,0.00,0.00,1.00,0.00,1.00,0.50,0.22,0.74,4.43,0.20,41.00,21.70,0,0.26,0.09,677664.00,153000.00,0.53,76428.97,3960000.00,1795833.00,0.00,-867.50,0.45,0.00
307509,456254,1,Cash loans,F,N,Y,0,171000.00,370107.00,20205.00,319500.00,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.01,-11961,-4786.00,-2562.00,-931,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.51,0.66,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,block of flats,0.01,"Stone, brick",No,0.00,0.00,0.00,0.00,-322.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.59,0.51,0.66,2.16,0.12,32.77,13.11,0,0.10,NaN,185053.50,85500.00,0.40,100478.43,45000.00,0.00,0.00,-1104.00,0.00,0.00
307510,456255,0,Cash loans,F,N,N,0,157500.00,675000.00,49117.50,675000.00,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.05,-16856,-1262.00,-5128.00,-410,1,1,1,1,1,0,Laborers,2.00,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.73,0.71,0.11,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.08,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,block of flats,0.07,Panel,No,0.00,0.00,0.00,0.00,-787.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,2.00,0.00,1.00,0.52,0.11,0.73,4.29,0.31,46.18,3.46,0,0.35,0.06,337500.00,78750.00,0.07,81739.93,3801919.50,1534913.01,0.00,-1089.45,0.40,0.00

In [282]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       ...
       'CREDIT...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [283]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.762547079975478

In [284]:
bureau.groupby("SK_ID_CURR").size()

SK_ID_CURR
100001     7
100002     8
100003     4
100004     2
100005     3
          ..
456249    13
456250     3
456253     4
456254     1
456255    11
Length: 305811, dtype: int64

In [285]:
bureau_loan_count = bureau.groupby("SK_ID_CURR").size().reset_index(name="BUREAU_LOAN_COUNT")

In [286]:
active_loans = (
    bureau[bureau["CREDIT_ACTIVE"] == "Active"]
    .groupby("SK_ID_CURR")
    .size()
    .reset_index(name="ACTIVE_LOAN_COUNT")
)

In [287]:
closed_loans = (
    bureau[bureau["CREDIT_ACTIVE"] == "Closed"]
    .groupby("SK_ID_CURR")
    .size()
    .reset_index(name="CLOSED_LOAN_COUNT")
)

In [288]:
overdue_loans = (
    bureau[bureau["CREDIT_DAY_OVERDUE"] > 0]
    .groupby("SK_ID_CURR")
    .size()
    .reset_index(name="OVERDUE_LOAN_COUNT")
)

In [289]:
max_overdue = (
    bureau.groupby("SK_ID_CURR")["AMT_CREDIT_SUM_OVERDUE"]
    .max()
    .reset_index(name="MAX_OVERDUE_AMOUNT")
)

In [290]:
avg_overdue_days = (
    bureau.groupby("SK_ID_CURR")["CREDIT_DAY_OVERDUE"]
    .mean()
    .reset_index(name="AVG_OVERDUE_DAYS")
)

In [291]:
recent_credit = (
    bureau.groupby("SK_ID_CURR")["DAYS_CREDIT"]
    .max()
    .reset_index(name="MOST_RECENT_CREDIT")
)

In [292]:
app_train = app_train.merge(bureau_loan_count, on="SK_ID_CURR", how="left")

In [293]:
app_train = app_train.merge(active_loans, on="SK_ID_CURR", how="left")

In [294]:
app_train = app_train.merge(closed_loans, on="SK_ID_CURR", how="left")

In [295]:
app_train = app_train.merge(overdue_loans, on="SK_ID_CURR", how="left")

In [296]:
app_train = app_train.merge(max_overdue, on="SK_ID_CURR", how="left")

In [297]:
app_train = app_train.merge(avg_overdue_days, on="SK_ID_CURR", how="left")

In [298]:
app_train = app_train.merge(recent_credit, on="SK_ID_CURR", how="left")

In [300]:
X = app_train.drop("TARGET", axis=1)
y = app_train["TARGET"]

In [301]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [302]:
num_cols = X.select_dtypes(include=["float64","int64"]).columns
cat_cols = X.select_dtypes(include=["object", "string"]).columns

In [308]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       ...
       'DAYS_C...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [309]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7640371578373599

In [329]:
feature_names = model.named_steps["preprocessing"].get_feature_names_out()

In [330]:
feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": model.named_steps["classifier"].feature_importances_
}).sort_values(by="importance", ascending=False)

print(feat_imp.head(30))

                                               feature  importance
89                                num__EXT_SOURCE_MEAN        0.05
90                                 num__EXT_SOURCE_MIN        0.03
91                                 num__EXT_SOURCE_MAX        0.02
145          cat__NAME_EDUCATION_TYPE_Higher education        0.01
122                                 cat__CODE_GENDER_F        0.01
123                                 cat__CODE_GENDER_M        0.01
148  cat__NAME_EDUCATION_TYPE_Secondary / secondary...        0.01
64                                num__FLAG_DOCUMENT_3        0.01
126                                cat__FLAG_OWN_CAR_Y        0.01
121            cat__NAME_CONTRACT_TYPE_Revolving loans        0.01
120                 cat__NAME_CONTRACT_TYPE_Cash loans        0.01
125                                cat__FLAG_OWN_CAR_N        0.01
95                                 num__EMPLOYED_YEARS        0.01
29                                   num__EXT_SOURCE_3        0.01
150                    cat__NAME_FAMILY_STATUS_Married        0.01
98                                num__EXT_SOURCE_PROD        0.01
24                         num__REG_CITY_NOT_LIVE_CITY        0.01
5                                 num__AMT_GOODS_PRICE        0.01
61                       num__DEF_60_CNT_SOCIAL_CIRCLE        0.01
19                    num__REGION_RATING_CLIENT_W_CITY        0.01
101                            num__EMPLOYED_AGE_RATIO        0.01
107                             num__DEBT_CREDIT_RATIO        0.01
143                      cat__NAME_INCOME_TYPE_Working        0.01
3                                      num__AMT_CREDIT        0.01
164                    cat__OCCUPATION_TYPE_Core staff        0.01
4                                     num__AMT_ANNUITY        0.01
140                cat__NAME_INCOME_TYPE_State servant        0.01
59                       num__DEF_30_CNT_SOCIAL_CIRCLE        0.01
228               cat__ORGANIZATION_TYPE_Self-employed        0.01
77                               num__FLAG_DOCUMENT_16        0.01

In [313]:
cols_to_check = [
    "ACTIVE_LOAN_COUNT",
    "OVERDUE_LOAN_COUNT",
    "MAX_OVERDUE_AMOUNT"
]

for col in cols_to_check:
    print(col, col in app_train.columns)

ACTIVE_LOAN_COUNT True
OVERDUE_LOAN_COUNT True
MAX_OVERDUE_AMOUNT True

In [314]:
app_train[cols_to_check].isnull().mean()

ACTIVE_LOAN_COUNT    0.29
OVERDUE_LOAN_COUNT   0.99
MAX_OVERDUE_AMOUNT   0.14
dtype: float64

In [337]:
app_train["ACTIVE_LOAN_RATIO"] = (
    app_train["ACTIVE_LOAN_COUNT"] /
    app_train["BUREAU_LOAN_COUNT"] + 1
)

In [338]:
app_train["OVERDUE_LOAN_RATIO"] = (
    app_train["OVERDUE_LOAN_COUNT"] /
    app_train["BUREAU_LOAN_COUNT"] + 1
)

In [339]:
app_train["CLOSED_LOAN_RATIO"] = (
    app_train["CLOSED_LOAN_COUNT"] /
    app_train["BUREAU_LOAN_COUNT"] + 1
)

In [318]:
recent_active = bureau[
    (bureau["CREDIT_ACTIVE"] == "Active") &
    (bureau["DAYS_CREDIT"] > -365)
]

In [319]:
recent_active_count = (
    recent_active.groupby("SK_ID_CURR")
    .size()
    .reset_index(name="RECENT_ACTIVE_LOAN_COUNT")
)

In [320]:
app_train = app_train.merge(
    recent_active_count,
    on="SK_ID_CURR",
    how="left"
)

In [321]:
app_train.replace([np.inf, -np.inf], np.nan, inplace=True)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_MEAN,EXT_SOURCE_MIN,EXT_SOURCE_MAX,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,AGE_YEARS,EMPLOYED_YEARS,EMPLOYED_ANOMALY,EXT_SOURCE_STD,EXT_SOURCE_PROD,CREDIT_PER_PERSON,INCOME_PER_PERSON,EMPLOYED_AGE_RATIO,EXT_SOURCE_INCOME,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT,DEBT_CREDIT_RATIO,OVERDUE_RATIO,BUREAU_LOAN_COUNT,ACTIVE_LOAN_COUNT,CLOSED_LOAN_COUNT,OVERDUE_LOAN_COUNT,MAX_OVERDUE_AMOUNT,AVG_OVERDUE_DAYS,MOST_RECENT_CREDIT,ACTIVE_LOAN_RATIO,OVERDUE_LOAN_RATIO,CLOSED_LOAN_RATIO,RECENT_ACTIVE_LOAN_COUNT
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637.00,-3648.00,-2120,1,1,0,1,1,0,Laborers,1.00,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.08,0.26,0.14,0.02,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,block of flats,0.01,"Stone, brick",No,2.00,2.00,2.00,2.00,-1134.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00,0.16,0.08,0.26,2.01,0.12,25.92,1.75,0,0.09,0.00,406597.50,202500.00,0.07,32761.89,865055.56,245781.00,0.00,-874.00,0.28,0.00,8.00,2.00,6.00,NaN,0.00,0.00,-103.00,0.25,NaN,0.75,1.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188.00,-1186.00,-291,1,1,0,1,1,0,Core staff,2.00,1,1,MONDAY,11,0,0,0,0,0,0,School,0.31,0.62,NaN,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.05,0.01,0.09,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.00,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.01,block of flats,0.07,Block,No,1.00,0.00,1.00,0.00,-828.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.47,0.31,0.62,4.79,0.13,45.93,3.25,0,0.22,NaN,646751.25,135000.00,0.07,126024.27,1017400.50,0.00,0.00,-1400.75,0.00,0.00,4.00,1.00,3.00,NaN,0.00,0.00,-606.00,0.25,NaN,0.75,NaN
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225.00,-4260.00,-2531,1,1,1,1,1,0,Laborers,1.00,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.56,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-815.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.64,0.56,0.73,2.00,0.10,52.18,0.62,0,0.12,NaN,135000.00,67500.00,0.01,43384.91,189037.80,0.00,0.00,-867.00,0.00,0.00,2.00,NaN,2.00,NaN,0.00,0.00,-408.00,NaN,NaN,1.00,NaN
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039.00,-9833.00,-2437,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.00,2.00,0.00,-617.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.65,0.65,0.65,2.32,0.22,52.07,8.33,0,NaN,NaN,156341.25,67500.00,0.16,87809.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038.00,-4311.00,-3458,1,1,0,1,0,0,Core staff,1.00,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-1106.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.32,0.32,0.32,4.22,0.18,54.61,8.32,0,NaN,NaN,513000.00,121500.00,0.15,39212.70,146250.00,0.00,0.00,-1149.00,0.00,0.00,1.00,NaN,1.00,NaN,0.00,0.00,-1149.00,NaN,NaN,1.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.00,254700.00,27558.00,225000.00,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.03,-9327,-236.00,-8456.00,-1982,1,1,0,1,0,0,Sales staff,1.00,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.15,0.68,NaN,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,0.10,0.02,0.98,0.08,0.03,0.46,0.01,0.09,0.01,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,block of flats,0.29,"Stone, brick",No,0.00,0.00,0.00,0.00,-273.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.41,0.15,0.68,1.62,0.17,25.55,0.65,0,0.38,NaN,254700.00,157500.00,0.03,65142.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.00,269550.00,12001.50,225000.00,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.03,-20775,NaN,-4388.00,-4090,1,0,0,1,1,0,NaN,1.00,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.12,NaN,0.02,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.05,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,block of flats,0.02,"Stone, brick",No,0.00,0.00,0.00,0.00,0.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.12,0.12,0.12,3.74,0.17,56.92,1000.67,1,NaN,NaN,269550.00,72000.00,17.58,8351.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.00,677664.00,29979.00,585000.00,Unaccompanied,Working,Higher education,Separated,House / apartment,0.01,-14966,-7921.00,-6737.00,-5150,1,1,0,1,0,1,Managers,1.00,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.74,0.54,0.22,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.93,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.97,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.94,0.00,block of flats,0.80,Panel,No,6.00,0.00,6.00,0.00,-1909.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.00,0.00,0.00,1.00,0.00,1.00,0.50,0.22,0.74,4.43,0.20,41.00,21.70,0,0.26,0.09,677664.00,153000.00,0.53,76428.97,3960000.00,1795833.00,0.00,-867.50,0.45,0.00,4.00,2.00,2.00,NaN,0.00,0.00,-713.00,0.50,NaN,0.50,NaN
307509,456254,1,Cash loans,F,N,Y,0,171000.00,370107.00,20205.00,319500.00,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.01,-11961,-4786.00,-2562.00,-931,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.51,0.66,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,block of flats,0.01,"Stone, brick",No,0.00,0.00,0.00,0.00,-322.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.59,0.51,0.66,2.16,0.12,32.77,13.11,0,0.10,NaN,185053.50,85500.00,0.40,100478.43,45000.00,0.00,0.00,-1104.00,0.00,0.00,1.00,NaN,1.00,NaN,0.00,0.00,-1104.00,NaN,NaN,1.00,NaN
307510,456255,0,Cash loans,F,N,N,0,157500.00,675000.00,49117.50,675000.00,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.05,-16856,-1262.00,-5128.00,-410,1,1,1,1,1,0,Laborers,2.00,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.73,0.71,0.11,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.08,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,block of flats,0.07,Panel,No,0.00,0.00,0.00,0.00,-787.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,2.00,0.00,1.00,0.52,0.11,0.73,4.29,0.31,46.18,3.46,0,0.35,0.06,337500.00,78750.00,0.07,81739.93,3801919.50,1534913.01,0.00,-1089.45,0.40,0.00,11.00,5.00,6.00,NaN,0.00,0.00,-363.00,0.45,NaN,0.55,1.00

In [327]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       ...
       'ACTIVE...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [328]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7638906282211712

In [331]:
app_train.to_pickle("app_train_till_bureau.pkl")

In [332]:
prev = pd.read_csv(r"D:\Projects\credit-risk-default-prediction\data\raw\previous_application.csv")

In [333]:
prev_app_count = (
    prev.groupby("SK_ID_CURR")
    .size()
    .reset_index(name="PREV_APP_COUNT")
)

In [334]:
approved_count = (
    prev[prev["NAME_CONTRACT_STATUS"] == "Approved"]
    .groupby("SK_ID_CURR")
    .size()
    .reset_index(name="APPROVED_COUNT")
)

In [335]:
refused_count = (
    prev[prev["NAME_CONTRACT_STATUS"] == "Refused"]
    .groupby("SK_ID_CURR")
    .size()
    .reset_index(name="REFUSED_COUNT")
)

In [345]:
mean_app_amt = (
    prev.groupby("SK_ID_CURR")["AMT_APPLICATION"]
    .mean()
    .reset_index(name="MEAN_AMT_APPLICATION")
)

In [346]:
mean_credit_amt = (
    prev.groupby("SK_ID_CURR")["AMT_CREDIT"]
    .mean()
    .reset_index(name="MEAN_AMT_CREDIT")
)

In [347]:
prev_features = prev_app_count.copy()

In [348]:
prev_features = prev_features.merge(
    approved_count,
    on="SK_ID_CURR",
    how="left"
)

In [349]:
prev_features = prev_features.merge(
    refused_count,
    on="SK_ID_CURR",
    how="left"
)

In [350]:
prev_features = prev_features.merge(
    mean_app_amt,
    on="SK_ID_CURR",
    how="left"
)

In [351]:
prev_features = prev_features.merge(
    mean_credit_amt,
    on="SK_ID_CURR",
    how="left"
)

In [352]:
count_cols = ["APPROVED_COUNT", "REFUSED_COUNT"]

prev_features[count_cols] = (
    prev_features[count_cols]
    .fillna(0)
)

In [353]:
prev_features["APPROVAL_RATIO"] = (
    prev_features["APPROVED_COUNT"] /
    (prev_features["PREV_APP_COUNT"] + 1)
)

In [354]:
prev_features["APP_CREDIT_DIFF"] = (
    prev_features["MEAN_AMT_APPLICATION"] -
    prev_features["MEAN_AMT_CREDIT"]
)

In [355]:
app_train = app_train.merge(
    prev_features,
    on="SK_ID_CURR",
    how="left"
)

In [356]:
app_train.replace([np.inf, -np.inf], np.nan, inplace=True)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_MEAN,EXT_SOURCE_MIN,EXT_SOURCE_MAX,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,AGE_YEARS,EMPLOYED_YEARS,EMPLOYED_ANOMALY,EXT_SOURCE_STD,EXT_SOURCE_PROD,CREDIT_PER_PERSON,INCOME_PER_PERSON,EMPLOYED_AGE_RATIO,EXT_SOURCE_INCOME,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT,DEBT_CREDIT_RATIO,OVERDUE_RATIO,BUREAU_LOAN_COUNT,ACTIVE_LOAN_COUNT,CLOSED_LOAN_COUNT,OVERDUE_LOAN_COUNT,MAX_OVERDUE_AMOUNT,AVG_OVERDUE_DAYS,MOST_RECENT_CREDIT,ACTIVE_LOAN_RATIO,OVERDUE_LOAN_RATIO,CLOSED_LOAN_RATIO,RECENT_ACTIVE_LOAN_COUNT,PREV_APP_COUNT,APPROVED_COUNT,REFUSED_COUNT,MEAN_AMT_APPLICATION,MEAN_AMT_CREDIT,APPROVAL_RATIO,APP_CREDIT_DIFF
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637.00,-3648.00,-2120,1,1,0,1,1,0,Laborers,1.00,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.08,0.26,0.14,0.02,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,block of flats,0.01,"Stone, brick",No,2.00,2.00,2.00,2.00,-1134.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00,0.16,0.08,0.26,2.01,0.12,25.92,1.75,0,0.09,0.00,406597.50,202500.00,0.07,32761.89,865055.56,245781.00,0.00,-874.00,0.28,0.00,8.00,2.00,6.00,NaN,0.00,0.00,-103.00,1.25,NaN,1.75,1.00,1.00,1.00,0.00,179055.00,179055.00,0.50,0.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188.00,-1186.00,-291,1,1,0,1,1,0,Core staff,2.00,1,1,MONDAY,11,0,0,0,0,0,0,School,0.31,0.62,NaN,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.05,0.01,0.09,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.00,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.01,block of flats,0.07,Block,No,1.00,0.00,1.00,0.00,-828.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.47,0.31,0.62,4.79,0.13,45.93,3.25,0,0.22,NaN,646751.25,135000.00,0.07,126024.27,1017400.50,0.00,0.00,-1400.75,0.00,0.00,4.00,1.00,3.00,NaN,0.00,0.00,-606.00,1.25,NaN,1.75,NaN,3.00,3.00,0.00,435436.50,484191.00,0.75,-48754.50
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225.00,-4260.00,-2531,1,1,1,1,1,0,Laborers,1.00,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.56,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-815.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.64,0.56,0.73,2.00,0.10,52.18,0.62,0,0.12,NaN,135000.00,67500.00,0.01,43384.91,189037.80,0.00,0.00,-867.00,0.00,0.00,2.00,NaN,2.00,NaN,0.00,0.00,-408.00,NaN,NaN,2.00,NaN,1.00,1.00,0.00,24282.00,20106.00,0.50,4176.00
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039.00,-9833.00,-2437,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.00,2.00,0.00,-617.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.65,0.65,0.65,2.32,0.22,52.07,8.33,0,NaN,NaN,156341.25,67500.00,0.16,87809.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.00,5.00,1.00,272203.26,291695.50,0.50,-19492.24
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038.00,-4311.00,-3458,1,1,0,1,0,0,Core staff,1.00,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-1106.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.32,0.32,0.32,4.22,0.18,54.61,8.32,0,NaN,NaN,513000.00,121500.00,0.15,39212.70,146250.00,0.00,0.00,-1149.00,0.00,0.00,1.00,NaN,1.00,NaN,0.00,0.00,-1149.00,NaN,NaN,2.00,NaN,6.00,6.00,0.00,150530.25,166638.75,0.86,-16108.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.00,254700.00,27558.00,225000.00,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.03,-9327,-236.00,-8456.00,-1982,1,1,0,1,0,0,Sales staff,1.00,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.15,0.68,NaN,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,0.10,0.02,0.98,0.08,0.03,0.46,0.01,0.09,0.01,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,block of flats,0.29,"Stone, brick",No,0.00,0.00,0.00,0.00,-273.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.41,0.15,0.68,1.62,0.17,25.55,0.65,0,0.38,NaN,254700.00,157500.00,0.03,65142.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,0.00,40455.00,40455.00,0.50,0.00
307507,456252,0,Cash loans,F,N,Y,0,72000.00,269550.00,12001.50,225000.00,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.03,-20775,NaN,-4388.00,-4090,1,0,0,1,1,0,NaN,1.00,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.12,NaN,0.02,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.05,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,block of flats,0.02,"Stone, brick",No,0.00,0.00,0.00,0.00,0.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.12,0.12,0.12,3.74,0.17,56.92,1000.67,1,NaN,NaN,269550.00,72000.00,17.58,8351.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,0.00,57595.50,56821.50,0.50,774.00
307508,456253,0,Cash loans,F,N,Y,0,153000.00,677664.00,29979.00,585000.00,Unaccompanied,Working,Higher education,Separated,House / apartment,0.01,-14966,-7921.00,-6737.00,-5150,1,1,0,1,0,1,Managers,1.00,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.74,0.54,0.22,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.93,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.97,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.94,0.00,block of flats,0.80,Panel,No,6.00,0.00,6.00,0.00,-1909.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.00,0.00,0.00,1.00,0.00,1.00,0.50,0.22,0.74,4.43,0.20,41.00,21.70,0,0.26,0.09,677664.00,153000.00,0.53,76428.97,3960000.00,1795833.00,0.00,-867.50,0.45,0.00,4.00,2.00,2.00,NaN,0.00,0.00,-713.00,1.50,NaN,1.50,NaN,2.00,2.00,0.00,24162.75,20625.75,0.67,3537.00
307509,456254,1,Cash loans,F,N,Y,0,171000.00,370107.00,20205.00,319500.00,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.01,-11961,-4786.00,-2562.00,-931,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.51,0.66,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,block of flats,0.01,"Stone, brick",No,0.00,0.00,0.00,0.00,-322.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.59,0.51,0.66,2.16,0.12,32.77,13.11,0,0.10,NaN,185053.50,85500.00,0.40,100478.43,45000.00,0.00,0.00,-1104.00,0.00,0.00,1.00,NaN,1.00,NaN,0.00,0.00,-1104.00,NaN,NaN,2.00,NaN,2.00,2.00,0.00,121317.75,134439.75,0.67,-13122.00
307510,456255,0,Cash loans,F,N,N,0,157500.00,675000.00,49117.50,675000.00,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.05,-16856,-1262.00,-5128.00,-410,1,1,1,1,1,0,Laborers,2.00,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.73,0.71,0.11,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.08,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,block of flats,0.07,Panel,No,0.00,0.00,0.00,0.00,-787.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,2.00,0.00,1.00,0.52,0.11,0.73,4.29,0.31,46.18,3.46,0,0.35,0.06,337500.00,78750.00,0.07,81739.93,3801919.50,1534913.01,0.00,-1089.45,0.40,0.00,11.00,5.00,6.00,NaN,0.00,0.00,-363.00,1.45,NaN,1.55,1.00,8.00,6.00,2.00,362770.88,424431.00,0.67,-61660.12

In [359]:

X = app_train.drop("TARGET", axis=1)
y = app_train["TARGET"]

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

num_cols = X.select_dtypes(include=["int64", "float64"]).columns
cat_cols = X.select_dtypes(include=["object", "string"]).columns


from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBClassifier

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])


preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])


model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])

In [360]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SK_ID_CURR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       ...
       'OVERDU...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [361]:
y_pred_proba = model.predict_proba(X_valid)[:, 1]
roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7687553420122185

In [362]:
feature_names = model.named_steps["preprocessing"].get_feature_names_out()

feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": model.named_steps["classifier"].feature_importances_
}).sort_values(by="importance", ascending=False)

print(feat_imp.head(40))

                                               feature  importance
89                                num__EXT_SOURCE_MEAN        0.08
91                                 num__EXT_SOURCE_MAX        0.02
90                                 num__EXT_SOURCE_MIN        0.02
152          cat__NAME_EDUCATION_TYPE_Higher education        0.01
130                                 cat__CODE_GENDER_M        0.01
64                                num__FLAG_DOCUMENT_3        0.01
155  cat__NAME_EDUCATION_TYPE_Secondary / secondary...        0.01
133                                cat__FLAG_OWN_CAR_Y        0.01
129                                 cat__CODE_GENDER_F        0.01
150                      cat__NAME_INCOME_TYPE_Working        0.01
132                                cat__FLAG_OWN_CAR_N        0.01
95                                 num__EMPLOYED_YEARS        0.01
125                                num__APPROVAL_RATIO        0.01
128            cat__NAME_CONTRACT_TYPE_Revolving loans        0.01
29                                   num__EXT_SOURCE_3        0.01
5                                 num__AMT_GOODS_PRICE        0.01
107                             num__DEBT_CREDIT_RATIO        0.01
127                 cat__NAME_CONTRACT_TYPE_Cash loans        0.01
3                                      num__AMT_CREDIT        0.01
113                            num__MAX_OVERDUE_AMOUNT        0.01
122                                 num__REFUSED_COUNT        0.01
19                    num__REGION_RATING_CLIENT_W_CITY        0.01
157                    cat__NAME_FAMILY_STATUS_Married        0.01
59                       num__DEF_30_CNT_SOCIAL_CIRCLE        0.01
98                                num__EXT_SOURCE_PROD        0.01
119                      num__RECENT_ACTIVE_LOAN_COUNT        0.01
105                        num__AMT_CREDIT_SUM_OVERDUE        0.01
147                cat__NAME_INCOME_TYPE_State servant        0.01
171                    cat__OCCUPATION_TYPE_Core staff        0.01
4                                     num__AMT_ANNUITY        0.01
24                         num__REG_CITY_NOT_LIVE_CITY        0.01
61                       num__DEF_60_CNT_SOCIAL_CIRCLE        0.01
94                                      num__AGE_YEARS        0.01
108                                 num__OVERDUE_RATIO        0.01
101                            num__EMPLOYED_AGE_RATIO        0.01
121                                num__APPROVED_COUNT        0.01
116                             num__ACTIVE_LOAN_RATIO        0.01
7                                      num__DAYS_BIRTH        0.01
96                               num__EMPLOYED_ANOMALY        0.01
235               cat__ORGANIZATION_TYPE_Self-employed        0.01

In [363]:
installments = pd.read_csv(r"D:\Projects\credit-risk-default-prediction\data\raw\installments_payments.csv")

In [364]:
installments["PAYMENT_DELAY"] = (
    installments["DAYS_ENTRY_PAYMENT"] -
    installments["DAYS_INSTALMENT"]
)

In [365]:
installments["PAYMENT_RATIO"] = (
    installments["AMT_PAYMENT"] /
    (installments["AMT_INSTALMENT"] + 1)
)

In [366]:
installments["LATE_PAYMENT"] = (
    installments["PAYMENT_DELAY"] > 0
).astype(int)

In [367]:
mean_delay = (
    installments.groupby("SK_ID_CURR")["PAYMENT_DELAY"]
    .mean()
    .reset_index(name="MEAN_PAYMENT_DELAY")
)

In [368]:
max_delay = (
    installments.groupby("SK_ID_CURR")["PAYMENT_DELAY"]
    .max()
    .reset_index(name="MAX_PAYMENT_DELAY")
)

In [369]:
mean_payment_ratio = (
    installments.groupby("SK_ID_CURR")["PAYMENT_RATIO"]
    .mean()
    .reset_index(name="MEAN_PAYMENT_RATIO")
)

In [370]:
late_payment_count = (
    installments.groupby("SK_ID_CURR")["LATE_PAYMENT"]
    .sum()
    .reset_index(name="LATE_PAYMENT_COUNT")
)

In [371]:
inst_features = mean_delay.copy()

In [372]:
inst_features = inst_features.merge(
    max_delay,
    on="SK_ID_CURR",
    how="left"
)

In [373]:
inst_features = inst_features.merge(
    mean_payment_ratio,
    on="SK_ID_CURR",
    how="left"
)

In [374]:
inst_features = inst_features.merge(
    late_payment_count,
    on="SK_ID_CURR",
    how="left"
)

In [375]:
app_train = app_train.merge(
    inst_features,
    on="SK_ID_CURR",
    how="left"
)

In [376]:
app_train.replace([np.inf, -np.inf], np.nan, inplace=True)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_MEAN,EXT_SOURCE_MIN,EXT_SOURCE_MAX,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,AGE_YEARS,EMPLOYED_YEARS,EMPLOYED_ANOMALY,EXT_SOURCE_STD,EXT_SOURCE_PROD,CREDIT_PER_PERSON,INCOME_PER_PERSON,EMPLOYED_AGE_RATIO,EXT_SOURCE_INCOME,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT,DEBT_CREDIT_RATIO,OVERDUE_RATIO,BUREAU_LOAN_COUNT,ACTIVE_LOAN_COUNT,CLOSED_LOAN_COUNT,OVERDUE_LOAN_COUNT,MAX_OVERDUE_AMOUNT,AVG_OVERDUE_DAYS,MOST_RECENT_CREDIT,ACTIVE_LOAN_RATIO,OVERDUE_LOAN_RATIO,CLOSED_LOAN_RATIO,RECENT_ACTIVE_LOAN_COUNT,PREV_APP_COUNT,APPROVED_COUNT,REFUSED_COUNT,MEAN_AMT_APPLICATION,MEAN_AMT_CREDIT,APPROVAL_RATIO,APP_CREDIT_DIFF,MEAN_PAYMENT_DELAY,MAX_PAYMENT_DELAY,MEAN_PAYMENT_RATIO,LATE_PAYMENT_COUNT
0,100002,1,Cash loans,M,N,Y,0,202500.00,406597.50,24700.50,351000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.02,-9461,-637.00,-3648.00,-2120,1,1,0,1,1,0,Laborers,1.00,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.08,0.26,0.14,0.02,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,0.03,0.04,0.97,0.00,0.07,0.08,0.04,0.02,0.00,block of flats,0.01,"Stone, brick",No,2.00,2.00,2.00,2.00,-1134.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00,0.16,0.08,0.26,2.01,0.12,25.92,1.75,0,0.09,0.00,406597.50,202500.00,0.07,32761.89,865055.56,245781.00,0.00,-874.00,0.28,0.00,8.00,2.00,6.00,NaN,0.00,0.00,-103.00,1.25,NaN,1.75,1.00,1.00,1.00,0.00,179055.00,179055.00,0.50,0.00,-20.42,-12.00,1.00,0.00
1,100003,0,Cash loans,F,N,N,0,270000.00,1293502.50,35698.50,1129500.00,Family,State servant,Higher education,Married,House / apartment,0.00,-16765,-1188.00,-1186.00,-291,1,1,0,1,1,0,Core staff,2.00,1,1,MONDAY,11,0,0,0,0,0,0,School,0.31,0.62,NaN,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.05,0.01,0.09,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.00,0.10,0.05,0.99,0.08,0.03,0.29,0.01,0.06,0.01,block of flats,0.07,Block,No,1.00,0.00,1.00,0.00,-828.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.47,0.31,0.62,4.79,0.13,45.93,3.25,0,0.22,NaN,646751.25,135000.00,0.07,126024.27,1017400.50,0.00,0.00,-1400.75,0.00,0.00,4.00,1.00,3.00,NaN,0.00,0.00,-606.00,1.25,NaN,1.75,NaN,3.00,3.00,0.00,435436.50,484191.00,0.75,-48754.50,-7.16,-1.00,1.00,0.00
2,100004,0,Revolving loans,M,Y,Y,0,67500.00,135000.00,6750.00,135000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.01,-19046,-225.00,-4260.00,-2531,1,1,1,1,1,0,Laborers,1.00,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.56,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-815.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.64,0.56,0.73,2.00,0.10,52.18,0.62,0,0.12,NaN,135000.00,67500.00,0.01,43384.91,189037.80,0.00,0.00,-867.00,0.00,0.00,2.00,NaN,2.00,NaN,0.00,0.00,-408.00,NaN,NaN,2.00,NaN,1.00,1.00,0.00,24282.00,20106.00,0.50,4176.00,-7.67,-3.00,1.00,0.00
3,100006,0,Cash loans,F,N,Y,0,135000.00,312682.50,29686.50,297000.00,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.01,-19005,-3039.00,-9833.00,-2437,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.00,2.00,0.00,-617.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.65,0.65,0.65,2.32,0.22,52.07,8.33,0,NaN,NaN,156341.25,67500.00,0.16,87809.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.00,5.00,1.00,272203.26,291695.50,0.50,-19492.24,-19.38,-1.00,1.00,0.00
4,100007,0,Cash loans,M,N,Y,0,121500.00,513000.00,21865.50,513000.00,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.03,-19932,-3038.00,-4311.00,-3458,1,1,0,1,0,0,Core staff,1.00,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,-1106.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.32,0.32,0.32,4.22,0.18,54.61,8.32,0,NaN,NaN,513000.00,121500.00,0.15,39212.70,146250.00,0.00,0.00,-1149.00,0.00,0.00,1.00,NaN,1.00,NaN,0.00,0.00,-1149.00,NaN,NaN,2.00,NaN,6.00,6.00,0.00,150530.25,166638.75,0.86,-16108.50,-3.64,12.00,0.95,16.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.00,254700.00,27558.00,225000.00,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.03,-9327,-236.00,-8456.00,-1982,1,1,0,1,0,0,Sales staff,1.00,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.15,0.68,NaN,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,0.10,0.02,0.98,0.08,0.03,0.46,0.01,0.09,0.01,0.20,0.09,0.99,0.22,0.10,0.60,0.06,0.20,0.11,block of flats,0.29,"Stone, brick",No,0.00,0.00,0.00,0.00,-273.00,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.41,0.15,0.68,1.62,0.17,25.55,0.65,0,0.38,NaN,254700.00,157500.00,0.03,65142.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,0.00,40455.00,40455.00,0.50,0.00,-36.29,-8.00,1.00,0.00
307507,456252,0,Cash loans,F,N,Y,0,72000.00,269550.00,12001.50,225000.00,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.03,-20775,NaN,-4388.00,-4090,1,0,0,1,1,0,NaN,1.00,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.12,NaN,0.02,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.05,0.97,0.00,0.10,0.08,0.06,0.03,0.00,0.03,0.04,0.97,0.00,0.10,0.08,0.06,0.03,0.00,block of flats,0.02,"Stone, brick",No,0.00,0.00,0.00,0.00,0.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.12,0.12,0.12,3.74,0.17,56.92,1000.67,1,NaN,NaN,269550.00,72000.00,17.58,8351.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,0.00,57595.50,56821.50,0.50,774.00,-2.83,3.00,1.00,1.00
307508,456253,0,Cash loans,F,N,Y,0,153000.00,677664.00,29979.00,585000.00,Unaccompanied,Working,Higher education,Separated,House / apartment,0.01,-14966,-7921.00,-6737.00,-5150,1,1,0,1,0,1,Managers,1.00,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.74,0.54,0.22,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.93,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.97,0.00,0.10,0.09,0.98,0.00,0.21,0.17,NaN,0.94,0.00,block of flats,0.80,Panel,No,6.00,0.00,6.00,0.00,-1909.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.00,0.00,0.00,1.00,0.00,1.00,0.50,0.22,0.74,4.43,0.20,41.00,21.70,0,0.26,0.09,677664.00,153000.00,0.53,76428.97,3960000.00,1795833.00,0.00,-867.50,0.45,0.00,4.00,2.00,2.00,NaN,0.00,0.00,-713.00,1.50,NaN,1.50,NaN,2.00,2.00,0.00,24162.75,20625.75,0.67,3537.00,-14.50,9.00,0.93,1.00
307509,456254,1,Cash loans,F,N,Y,0,171000.00,370107.00,20205.00,319500.00,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.01,-11961,-4786.00,-2562.00,-931,1,1,0,1,0,0,Laborers,2.00,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.51,0.66,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,0.01,NaN,0.98,NaN,0.07,0.04,NaN,0.01,NaN,block of flats,0.01,"Stone, brick",No,0.00,0.00,0.00,0.00,-322.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.59,0.51,0.66,2.16,0.12,32.77,13.11,0,0.10,NaN,185053.50,85500.00,0.40,100478.43,45000.00,0.00,0.00,-1104.00,0.00,0.00,1.00,NaN,1.00,NaN,0.00,0.00,-1104.00,NaN,NaN,2.00,NaN,2.00,2.00,0.00,121317.75,134439.75,0.67,-13122.00,-19.00,-8.00,1.00,0.00
307510,456255,0,Cash loans,F,N,N,0,157500.00,675000.00,49117.50,675000.00,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.05,-16856,-1262.00,-5128.00,-410,1,1,1,1,1,0,Laborers,2.00,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.73,0.71,0.11,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.08,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,0.07,0.05,0.99,0.08,0.07,0.38,NaN,0.08,0.00,block of flats,0.07,Panel,No,0.00,0.00,0.00,0.00,-787.00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,2.00,0.00,1.00,0.52,0.11,0.73,4.29,0.31,46.18,3.46,0,0.35,0.06,337500.00,78750.00,0.07,81739.93,3801919.50,1534913.01,0.00,-1089.45,0.40,0.00,11.00,5.00,6.00,NaN,0.00,0.00,-363.00,1.45,NaN,1.55,1.00,8.00,6.00,2.00,362770.88,424431.00,0.67,-61660.12,-8.07,7.00,1.03,14.00

In [377]:
app_train.to_pickle("app_train_till_installments.pkl")

In [378]:
# =========================
# REBUILD X AND y
# =========================

X = app_train.drop("TARGET", axis=1)
y = app_train["TARGET"]


# =========================
# TRAIN VALID SPLIT
# =========================

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# =========================
# COLUMN LISTS
# =========================

num_cols = X.select_dtypes(include=["int64", "float64"]).columns
cat_cols = X.select_dtypes(include=["object", "string"]).columns


# =========================
# PIPELINES
# =========================

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])


# =========================
# PREPROCESSOR
# =========================

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])


# =========================
# MODEL PIPELINE
# =========================

from xgboost import XGBClassifier

model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    ))
])


# =========================
# TRAIN MODEL
# =========================

model.fit(X_train, y_train)


# =========================
# EVALUATE
# =========================

from sklearn.metrics import roc_auc_score

y_pred_proba = model.predict_proba(X_valid)[:, 1]

roc_auc = roc_auc_score(y_valid, y_pred_proba)

print(roc_auc)

0.7742334193541355

In [379]:
feature_names = model.named_steps["preprocessing"].get_feature_names_out()

feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": model.named_steps["classifier"].feature_importances_
}).sort_values(by="importance", ascending=False)

print(feat_imp.head(40))

                                               feature  importance
89                                num__EXT_SOURCE_MEAN        0.09
90                                 num__EXT_SOURCE_MIN        0.02
91                                 num__EXT_SOURCE_MAX        0.01
134                                 cat__CODE_GENDER_M        0.01
156          cat__NAME_EDUCATION_TYPE_Higher education        0.01
159  cat__NAME_EDUCATION_TYPE_Secondary / secondary...        0.01
64                                num__FLAG_DOCUMENT_3        0.01
136                                cat__FLAG_OWN_CAR_N        0.01
133                                 cat__CODE_GENDER_F        0.01
125                                num__APPROVAL_RATIO        0.01
129                            num__MEAN_PAYMENT_RATIO        0.01
95                                 num__EMPLOYED_YEARS        0.01
154                      cat__NAME_INCOME_TYPE_Working        0.01
12                                 num__FLAG_EMP_PHONE        0.01
132            cat__NAME_CONTRACT_TYPE_Revolving loans        0.01
5                                 num__AMT_GOODS_PRICE        0.01
161                    cat__NAME_FAMILY_STATUS_Married        0.01
107                             num__DEBT_CREDIT_RATIO        0.01
19                    num__REGION_RATING_CLIENT_W_CITY        0.01
137                                cat__FLAG_OWN_CAR_Y        0.01
113                            num__MAX_OVERDUE_AMOUNT        0.01
59                       num__DEF_30_CNT_SOCIAL_CIRCLE        0.01
3                                      num__AMT_CREDIT        0.01
131                 cat__NAME_CONTRACT_TYPE_Cash loans        0.01
98                                num__EXT_SOURCE_PROD        0.01
175                    cat__OCCUPATION_TYPE_Core staff        0.01
101                            num__EMPLOYED_AGE_RATIO        0.01
29                                   num__EXT_SOURCE_3        0.01
121                                num__APPROVED_COUNT        0.01
110                             num__ACTIVE_LOAN_COUNT        0.01
151                cat__NAME_INCOME_TYPE_State servant        0.01
122                                 num__REFUSED_COUNT        0.01
239               cat__ORGANIZATION_TYPE_Self-employed        0.01
119                      num__RECENT_ACTIVE_LOAN_COUNT        0.01
4                                     num__AMT_ANNUITY        0.01
94                                      num__AGE_YEARS        0.01
61                       num__DEF_60_CNT_SOCIAL_CIRCLE        0.01
24                         num__REG_CITY_NOT_LIVE_CITY        0.01
251           cat__ORGANIZATION_TYPE_Transport: type 3        0.01
105                        num__AMT_CREDIT_SUM_OVERDUE        0.01

In [380]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [382]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="roc_auc",
    n_jobs=1
)

print(scores)
print(scores.mean())
print(scores.std())

[0.7685978  0.77820525 0.77111701 0.77498636 0.76820386]
0.7722220564464608
0.003845574561799376